// 內建啟動活動庫 —— 提供推薦引擎一組安全、可立即使用的種子活動。
// 正式環境應改由 companion_activities 資料表載入；此處作為離線 / 保底資料來源。

import type { Activity } from './recommendation'

export const STARTER_ACTIVITIES: Activity[] = [
  {
    id: 'newborn-soft-talk',
    title: '輕聲說今天',
    openingLine: '寶寶，我跟你說說我們今天做了什麼',
    steps: ['把寶寶抱在胸前', '用輕柔的聲音描述今天發生的小事', '觀察寶寶的眼神與回應'],
    requiredCapabilities: [],
    zpdTargets: ['respondsToName'],
    stimulationLevel: 'low',
    requiredResources: [],
    spaceRequirement: 'anywhere',
    minDurationMinutes: 3,
    maxDurationMinutes: 10,
    minAgeMonths: 0,
    maxAgeMonths: 6,
    isBedtimeSafe: true,
    isSickDaySafe: true,
    companionType: 'talk',
    costLevel: 'free',
    cleanupLevel: 'none',
    prepMinutes: 0,
  },
  {
    id: 'infant-peekaboo',
    title: '躲貓貓',
    openingLine: '我在哪裡呢？',
    steps: ['用雙手或小布巾遮住臉', '說「躲貓貓！」再露出臉', '配合寶寶的笑聲重複'],
    requiredCapabilities: ['respondsToName'],
    zpdTargets: ['objectPermanence'],
    stimulationLevel: 'medium',
    requiredResources: [],
    spaceRequirement: 'anywhere',
    minDurationMinutes: 3,
    maxDurationMinutes: 10,
    minAgeMonths: 4,
    maxAgeMonths: 12,
    isBedtimeSafe: false,
    isSickDaySafe: true,
    companionType: 'play',
    costLevel: 'free',
    cleanupLevel: 'none',
    prepMinutes: 0,
  },
  {
    id: 'sitting-stack-cups',
    title: '疊疊樂',
    openingLine: '我們一起把杯子疊高高',
    steps: ['拿出幾個塑膠杯', '示範疊起再推倒', '讓孩子自己嘗試'],
    requiredCapabilities: ['canSitUnsupported'],
    optionalCapabilities: ['canGrasp'],
    zpdTargets: ['canStackBlocks3', 'canPincerGrip'],
    stimulationLevel: 'medium',
    requiredResources: ['kitchen_items'],
    spaceRequirement: 'living_room',
    minDurationMinutes: 5,
    maxDurationMinutes: 15,
    minAgeMonths: 6,
    maxAgeMonths: 18,
    isBedtimeSafe: false,
    isSickDaySafe: true,
    companionType: 'play',
    costLevel: 'free',
    cleanupLevel: 'low',
    prepMinutes: 1,
  },
  {
    id: 'toddler-read-together',
    title: '一起看圖畫書',
    openingLine: '我們來看看這本書裡有什麼',
    steps: ['挑一本孩子喜歡的書', '指著圖畫說出名稱', '問孩子「這是什麼呀？」'],
    requiredCapabilities: ['canSitUnsupported'],
    optionalCapabilities: ['hasVocabulary10'],
    zpdTargets: ['usesTwoWordPhrases', 'usesSentences'],
    stimulationLevel: 'low',
    requiredResources: ['books'],
    spaceRequirement: 'anywhere',
    minDurationMinutes: 5,
    maxDurationMinutes: 20,
    minAgeMonths: 9,
    maxAgeMonths: 60,
    isBedtimeSafe: true,
    isSickDaySafe: true,
    companionType: 'read',
    costLevel: 'free',
    cleanupLevel: 'none',
    prepMinutes: 1,
  },
  {
    id: 'toddler-ball-roll',
    title: '滾球接力',
    openingLine: '球要滾過去囉，接住！',
    steps: ['兩人面對面坐下', '把球滾向對方', '輪流滾來滾去'],
    requiredCapabilities: ['canSitUnsupported'],
    zpdTargets: ['canTakeTurns'],
    stimulationLevel: 'high',
    requiredResources: ['balls'],
    spaceRequirement: 'living_room',
    minDurationMinutes: 5,
    maxDurationMinutes: 15,
    minAgeMonths: 9,
    maxAgeMonths: 48,
    isBedtimeSafe: false,
    isSickDaySafe: false,
    companionType: 'play',
    costLevel: 'free',
    cleanupLevel: 'low',
    prepMinutes: 0,
  },
  {
    id: 'walker-crayon-doodle',
    title: '蠟筆塗鴉',
    openingLine: '我們來畫畫，你想畫什麼顏色？',
    steps: ['鋪一張大紙', '一起塗鴉', '說出畫的顏色'],
    requiredCapabilities: ['canGrasp'],
    optionalCapabilities: ['canScribble'],
    zpdTargets: ['canScribble', 'canDrawCircle'],
    stimulationLevel: 'medium',
    requiredResources: ['paper_crayons'],
    spaceRequirement: 'living_room',
    minDurationMinutes: 10,
    maxDurationMinutes: 25,
    minAgeMonths: 15,
    maxAgeMonths: 60,
    isBedtimeSafe: false,
    isSickDaySafe: true,
    companionType: 'creative',
    costLevel: 'low',
    cleanupLevel: 'high',
    prepMinutes: 3,
  },
  {
    id: 'calm-cushion-breathing',
    title: '抱枕深呼吸',
    openingLine: '我們一起抱著抱枕，慢慢呼吸',
    steps: ['一起坐在抱枕上', '示範深吸氣、慢吐氣', '抱著孩子一起做三次'],
    requiredCapabilities: [],
    zpdTargets: ['selfSoothing', 'toleratesFrustration'],
    stimulationLevel: 'low',
    requiredResources: ['cushions'],
    spaceRequirement: 'anywhere',
    minDurationMinutes: 3,
    maxDurationMinutes: 10,
    minAgeMonths: 12,
    maxAgeMonths: 60,
    isBedtimeSafe: true,
    isSickDaySafe: true,
    companionType: 'calm_down',
    costLevel: 'free',
    cleanupLevel: 'none',
    prepMinutes: 0,
  },
  {
    id: 'preschool-pretend-shop',
    title: '扮家家酒開商店',
    openingLine: '歡迎光臨！你想買什麼呢？',
    steps: ['用家裡的小物當商品', '輪流當老闆和客人', '用對話完成買賣'],
    requiredCapabilities: ['usesTwoWordPhrases'],
    optionalCapabilities: ['symbolicPlay'],
    zpdTargets: ['cooperativePlay', 'canHaveConversation'],
    stimulationLevel: 'medium',
    requiredResources: [],
    spaceRequirement: 'anywhere',
    minDurationMinutes: 10,
    maxDurationMinutes: 30,
    minAgeMonths: 24,
    maxAgeMonths: 60,
    isBedtimeSafe: false,
    isSickDaySafe: true,
    companionType: 'play',
    costLevel: 'free',
    cleanupLevel: 'low',
    prepMinutes: 2,
  },
  {
    id: 'preschool-story-of-day',
    title: '說一說今天',
    openingLine: '你今天有什麼讓你開心的事嗎？',
    steps: ['坐在孩子旁邊', '問一個今天的小事', '認真聽並回應'],
    requiredCapabilities: ['usesSentences'],
    zpdTargets: ['canDescribeEvents', 'canHaveConversation'],
    stimulationLevel: 'low',
    requiredResources: [],
    spaceRequirement: 'anywhere',
    minDurationMinutes: 3,
    maxDurationMinutes: 15,
    minAgeMonths: 30,
    maxAgeMonths: 60,
    isBedtimeSafe: true,
    isSickDaySafe: true,
    companionType: 'talk',
    costLevel: 'free',
    cleanupLevel: 'none',
    prepMinutes: 0,
  },
]
