// 內容批次：6–12 個月（SITTING_BABY 6–9m + CRAWLER 9–12m）共 30 條。
//
// 設計依據：公開、通用的嬰兒發展里程碑共識——坐穩遊戲、爬行、扶站/扶走、
// 拇指食指夾取（pincer）、物體恆存、模仿動作、因果關係、第一個詞萌芽等。
// 所有活動：可安全在家、需成人全程看顧、無小零件窒息風險；高風險者標 ⚠️。
// 非醫療/評估內容，由 App 的免責聲明涵蓋。
//
// 欄位值需落在 schema 允許集合內（見 build-seed.mjs 驗證）。

export const activities = [
  // ===================== SITTING_BABY 6–9m =====================
  {
    title: '滾球來回',
    description: '坐姿下與寶寶來回滾球，練習坐穩、追視與輪流互動。',
    openingLine: '球球滾過去囉，換你滾回來～',
    steps: [
      '讓寶寶坐穩（必要時用枕頭護背）',
      '面對面把軟球慢慢滾向他',
      '鼓勵他用手擋住或推回',
      '一來一往多玩幾次',
    ],
    followUps: ['他會試著把球推回來嗎？'],
    safetyNotes: '球要大於寶寶口腔、材質柔軟；在地墊上進行。',
    endingLine: '滾得真好，球球休息囉。',
    minAge: 6,
    maxAge: 11,
    required: ['canSitUnsupported'],
    optional: [],
    zpd: [],
    focus: ['gross_motor', 'social_cognitive'],
    stimulation: 'medium',
    playType: 'parallel',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '撕紙沙沙',
    description: '一起撕安全的紙，練習雙手協調並感受聲音與觸感。',
    openingLine: '我們來撕紙，沙沙沙好好玩！',
    steps: ['給寶寶一張乾淨、夠大的紙', '示範用雙手撕開', '讓他自己嘗試', '一起聽撕紙的聲音'],
    followUps: ['他撕得開嗎？喜歡這個聲音嗎？'],
    safetyNotes: '用無毒、夠大的紙；全程看顧避免放入口吞食，撕完即收。',
    endingLine: '撕了好多片，我們收乾淨。',
    minAge: 6,
    maxAge: 11,
    required: [],
    optional: [],
    zpd: [],
    focus: ['fine_motor'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'sensory',
    fallback: false,
  },
  {
    title: '動物在說話',
    description: '指著動物圖卡或玩具發出叫聲，連結聲音與物件、擴充語言。',
    openingLine: '小狗說「汪汪」，小貓說什麼呢？',
    steps: ['拿動物圖卡或玩偶', '指著動物並發出叫聲', '停一下等他反應', '重複幾種常見動物'],
    followUps: ['他對哪種叫聲最有興趣？'],
    safetyNotes: null,
    endingLine: '動物們都跟你說再見囉。',
    minAge: 6,
    maxAge: 12,
    required: [],
    optional: [],
    zpd: ['meaningfulBabble'],
    focus: ['language'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'talk',
    fallback: false,
  },
  {
    title: '拍手學一學',
    description: '示範拍手，鼓勵寶寶模仿你的動作。',
    openingLine: '拍拍手，跟我一起拍拍拍！',
    steps: ['面對寶寶慢慢拍手', '握著他的小手一起拍', '放開讓他自己試', '他拍了就熱情稱讚'],
    followUps: ['他會自己拍手了嗎？'],
    safetyNotes: null,
    endingLine: '拍手好棒，給你拍拍！',
    minAge: 6,
    maxAge: 12,
    required: [],
    optional: [],
    zpd: ['imitatesActions'],
    focus: ['social_cognitive'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 2,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '戳戳點點書',
    description: '引導寶寶用食指指、戳圖片，練習食指分化與專注。',
    openingLine: '小手指出來，這是什麼呀？',
    steps: ['翻開一本圖大的書', '示範用食指點圖片並命名', '引導他用食指去戳', '他點到就說出名稱'],
    followUps: ['他會用一根手指指了嗎？'],
    safetyNotes: '硬頁或布書為佳；放口探索屬正常，全程看顧。',
    endingLine: '小手指好厲害，下次再看。',
    minAge: 7,
    maxAge: 12,
    required: [],
    optional: [],
    zpd: ['canPincerGrip'],
    focus: ['fine_motor', 'language'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'read',
    fallback: false,
  },
  {
    title: '套套疊疊杯',
    description: '用大小不同的杯子套疊，練習抓放與大小概念。',
    openingLine: '杯子一個套一個，疊高高～',
    steps: [
      '給寶寶幾個大小不同的安全杯',
      '示範把小杯放進大杯',
      '讓他自己抓放探索',
      '一起把杯子排排站',
    ],
    followUps: ['他會把杯子放進去或拿出來嗎？'],
    safetyNotes: '杯子需大於口腔、無小零件與尖角。',
    endingLine: '玩得真專心，收進籃子。',
    minAge: 7,
    maxAge: 13,
    required: [],
    optional: [],
    zpd: ['canPincerGrip'],
    focus: ['fine_motor', 'social_cognitive'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '布巾躲玩具',
    description: '用布蓋住玩具讓寶寶尋找，鞏固物體恆存概念。',
    openingLine: '玩具躲到布布下面了，找得到嗎？',
    steps: ['讓寶寶看你把玩具藏到布下', '問「玩具在哪裡？」', '鼓勵他掀開布找', '找到就一起歡呼'],
    followUps: ['他會主動掀布去找嗎？'],
    safetyNotes: '布只蓋玩具、不蓋寶寶口鼻。',
    endingLine: '找到了！你好厲害。',
    minAge: 6,
    maxAge: 12,
    required: [],
    optional: [],
    zpd: ['objectPermanence'],
    focus: ['social_cognitive'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '傳來傳去',
    description: '把玩具遞給寶寶、再請他遞回，練習給予與輪流。',
    openingLine: '玩具給你～可以還給我嗎？謝謝！',
    steps: ['把玩具遞到寶寶手上', '伸手說「給我」並等待', '他放手就熱情道謝', '再遞回去重複'],
    followUps: ['他願意把東西交給你嗎？'],
    safetyNotes: null,
    endingLine: '會分享了，真貼心。',
    minAge: 7,
    maxAge: 13,
    required: [],
    optional: [],
    zpd: [],
    focus: ['social_cognitive'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '打拍子唱歌',
    description: '唱熟悉兒歌並輕拍節奏，連結語言、聽覺與動作。',
    openingLine: '我們來唱歌，一起打拍子！',
    steps: [
      '抱著或面對寶寶唱一首兒歌',
      '配合節奏輕拍他的手或腿',
      '在重複句停頓製造期待',
      '反覆同一首加深熟悉',
    ],
    followUps: ['他會跟著擺動或出聲嗎？'],
    safetyNotes: null,
    endingLine: '唱得好開心，再來一首。',
    minAge: 6,
    maxAge: 13,
    required: [],
    optional: [],
    zpd: ['meaningfulBabble'],
    focus: ['language', 'social_cognitive'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'music',
    fallback: false,
  },
  {
    title: '咚咚小鼓',
    description: '敲打安全容器當鼓，體驗「敲擊→聲音」的因果。',
    openingLine: '咚咚咚，看看能敲出什麼聲音！',
    steps: [
      '給寶寶一個安全的盒子或鍋與木匙',
      '示範敲一敲發出聲音',
      '讓他自己敲',
      '配合節奏一起咚咚咚',
    ],
    followUps: ['他發現是自己敲出聲音的嗎？'],
    safetyNotes: '器具無小零件、邊緣鈍；音量勿過大。',
    endingLine: '小鼓手好棒，收起來囉。',
    minAge: 6,
    maxAge: 12,
    required: [],
    optional: [],
    zpd: [],
    focus: ['fine_motor', 'social_cognitive'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: true,
    elderly: true,
    companionType: 'sensory',
    fallback: false,
  },
  {
    title: '軟墊小山坡',
    description: '用墊子堆成小坡，鼓勵寶寶翻越、爬上，強化軀幹與四肢。',
    openingLine: '前面有小山坡，我們爬上去看看！',
    steps: ['用柔軟墊子堆出低緩小坡', '在另一頭放玩具吸引', '鼓勵他爬越過去', '在旁保護隨時接住'],
    followUps: ['他能自己爬過去嗎？'],
    safetyNotes: '坡度低緩、周圍鋪軟墊、全程在旁保護。',
    endingLine: '爬山成功，好厲害！',
    minAge: 7,
    maxAge: 12,
    required: [],
    optional: [],
    zpd: ['canCrawl'],
    focus: ['gross_motor'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: false,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '抱著輕拍入睡',
    description: '睡前抱著輕拍、哼唱，建立安定的入睡儀式。',
    openingLine: '今天玩得好棒，我們準備睡覺囉。',
    steps: [
      '調暗燈光、抱著寶寶',
      '用低穩聲音哼一首固定的歌',
      '配合呼吸輕拍背部',
      '想睡了放回床上仰睡',
    ],
    followUps: null,
    safetyNotes: '入睡務必仰睡、床面淨空、不放鬆軟物。',
    endingLine: '晚安，做個好夢。',
    minAge: 6,
    maxAge: 15,
    required: [],
    optional: [],
    zpd: ['selfSoothing'],
    focus: ['emotional'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'bedroom',
    minDur: 5,
    maxDur: 15,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'calm_down',
    fallback: false,
  },

  // ===================== CRAWLER 9–12m =====================
  {
    title: '鑽鑽小隧道',
    description: '鼓勵寶寶爬過抱枕或紙箱隧道，練習爬行與空間概念。',
    openingLine: '鑽進小隧道，另一頭有驚喜喔！',
    steps: ['用紙箱或抱枕排出短隧道', '你在另一頭呼喚他', '鼓勵他爬過來', '到達就抱抱歡呼'],
    followUps: ['他爬過去花了多久？'],
    safetyNotes: '隧道穩固不塌、出入口淨空、全程看顧。',
    endingLine: '鑽過來了，好棒的探險家！',
    minAge: 9,
    maxAge: 14,
    required: ['canCrawl'],
    optional: [],
    zpd: [],
    focus: ['gross_motor', 'social_cognitive'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: false,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '扶著沙發站',
    description: '在穩固家具旁放玩具，鼓勵寶寶扶著站起。',
    openingLine: '扶著站起來，拿上面的玩具！',
    steps: ['把玩具放在沙發或矮桌上緣', '讓寶寶扶著家具', '鼓勵他用力撐起站立', '在旁保護避免後仰'],
    followUps: ['他能扶著站多久？'],
    safetyNotes: '家具需穩固不傾倒、邊角包覆、地面鋪軟墊、全程保護。',
    endingLine: '站起來了，腿好有力！',
    minAge: 9,
    maxAge: 13,
    required: [],
    optional: [],
    zpd: ['canPullToStand'],
    focus: ['gross_motor'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: false,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '扶邊走一走',
    description: '沿著穩固家具放玩具，引導寶寶扶著側走（cruising）。',
    openingLine: '扶著邊邊，一步一步走走看～',
    steps: [
      '沿矮家具邊緣放幾個玩具',
      '讓寶寶扶著站好',
      '在稍遠處放玩具吸引他側移',
      '在旁保護隨時接住',
    ],
    followUps: ['他能扶著橫向移動幾步？'],
    safetyNotes: '家具穩固、路徑淨空、邊角包覆、全程在旁保護。',
    endingLine: '會扶著走了，好厲害！',
    minAge: 10,
    maxAge: 15,
    required: ['canPullToStand'],
    optional: [],
    zpd: ['canWalkIndependently'],
    focus: ['gross_motor'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: false,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '追滾滾球',
    description: '把球慢慢滾出，鼓勵寶寶爬過去追，結合移動與目標。',
    openingLine: '球球滾走囉，快爬去追！',
    steps: ['讓寶寶坐或趴在地墊上', '把軟球慢慢滾向不遠處', '鼓勵他爬過去拿', '拿到就一起歡呼'],
    followUps: ['他追到球了嗎？'],
    safetyNotes: '在淨空的軟墊區進行；球材質柔軟、夠大。',
    endingLine: '追到球了，爬得真快！',
    minAge: 9,
    maxAge: 13,
    required: ['canCrawl'],
    optional: [],
    zpd: [],
    focus: ['gross_motor'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: false,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '裝進倒出來',
    description: '把安全小物放進容器再倒出，練習抓放、因果與容量概念。',
    openingLine: '放進去～再倒出來，嘩啦！',
    steps: [
      '準備一個容器與幾個安全大物件',
      '示範放進去再倒出來',
      '讓寶寶自己裝、倒',
      '描述「進去」「出來」',
    ],
    followUps: ['他喜歡裝還是倒？'],
    safetyNotes: '物件須大於口腔、無小零件，全程看顧。',
    endingLine: '裝裝倒倒好好玩，收起來。',
    minAge: 9,
    maxAge: 15,
    required: [],
    optional: ['canPincerGrip'],
    zpd: [],
    focus: ['fine_motor', 'social_cognitive'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '翻翻硬頁書',
    description: '一起翻硬頁書、指圖命名，培養翻頁動作與閱讀興趣。',
    openingLine: '我們來翻書書，看看下一頁是什麼！',
    steps: ['抱著寶寶翻開硬頁書', '指圖慢慢命名', '鼓勵他自己翻頁', '對他指的圖給回應'],
    followUps: ['他會自己翻頁了嗎？'],
    safetyNotes: '硬頁書邊角圓鈍；放口探索屬正常。',
    endingLine: '看書書真棒，下次再讀。',
    minAge: 9,
    maxAge: 15,
    required: [],
    optional: [],
    zpd: ['hasVocabulary10'],
    focus: ['language', 'fine_motor'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'read',
    fallback: false,
  },
  {
    title: '跟我說「媽媽」',
    description: '清楚緩慢地示範第一個常用詞，鼓勵寶寶模仿發音。',
    openingLine: '看我的嘴巴：「媽—媽」，換你！',
    steps: [
      '面對寶寶，清楚說「媽媽」「爸爸」',
      '誇張嘴型讓他看',
      '停下來等他嘗試',
      '他發出近似音就熱情回應',
    ],
    followUps: ['他試著模仿哪個音？'],
    safetyNotes: null,
    endingLine: '你說得越來越像了！',
    minAge: 9,
    maxAge: 15,
    required: [],
    optional: [],
    zpd: ['hasVocabulary10'],
    focus: ['language'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 2,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'talk',
    fallback: false,
  },
  {
    title: '轉角躲貓貓',
    description: '在門邊或家具後短暫躲藏再出現，延伸物體恆存與期待感。',
    openingLine: '馬麻/把拔躲起來囉……出現！',
    steps: [
      '在寶寶看得到的家具旁短暫躲一下',
      '叫他的名字製造期待',
      '探頭出來說「出現！」',
      '換不同位置再玩',
    ],
    followUps: ['他會盯著你消失的地方等嗎？'],
    safetyNotes: '躲藏距離近、隨時看得到寶寶；家具穩固。',
    endingLine: '哈哈，又找到了！',
    minAge: 9,
    maxAge: 15,
    required: [],
    optional: [],
    zpd: ['objectPermanence'],
    focus: ['social_cognitive', 'emotional'],
    stimulation: 'medium',
    playType: 'parallel',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: false,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '我給你你給我',
    description: '輪流把玩具交給彼此，練習給予、等待與社交來回。',
    openingLine: '我給你，換你給我，謝謝你～',
    steps: [
      '遞玩具給寶寶說「給你」',
      '伸手說「給我」並微笑等待',
      '他交回就熱情道謝',
      '反覆建立輪流節奏',
    ],
    followUps: ['他懂得輪流的節奏了嗎？'],
    safetyNotes: null,
    endingLine: '會輪流了，真棒的好朋友！',
    minAge: 9,
    maxAge: 15,
    required: [],
    optional: [],
    zpd: [],
    focus: ['social_cognitive'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '模仿拍拍揮揮',
    description: '示範拍手、揮手、拍肚子等小動作，鼓勵寶寶模仿。',
    openingLine: '看我做，你也跟著做做看～',
    steps: [
      '做一個簡單動作（拍手）',
      '鼓勵寶寶模仿',
      '換下一個（揮手、拍肚子）',
      '他模仿成功就大力稱讚',
    ],
    followUps: ['他最會模仿哪個動作？'],
    safetyNotes: null,
    endingLine: '模仿得真像，好聰明！',
    minAge: 9,
    maxAge: 15,
    required: [],
    optional: [],
    zpd: ['imitatesActions'],
    focus: ['social_cognitive'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 2,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '按一按跳出來',
    description: '玩有按壓彈出機關的玩具，理解「我的動作→結果」。',
    openingLine: '按一下，看看會有什麼跳出來！',
    steps: ['準備有按壓/彈出機關的安全玩具', '示範按下讓它彈出', '引導他自己按', '彈出時一起驚呼'],
    followUps: ['他學會自己按了嗎？'],
    safetyNotes: '玩具無小零件、機關不夾手。',
    endingLine: '是你讓它跳出來的，好棒！',
    minAge: 9,
    maxAge: 15,
    required: [],
    optional: ['canPincerGrip'],
    zpd: [],
    focus: ['social_cognitive', 'fine_motor'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '找找響玩具',
    description: '把會發聲的玩具藏起，讓寶寶循聲尋找，結合聽覺與物體恆存。',
    openingLine: '聽，聲音在哪裡？我們去找找！',
    steps: [
      '用會響的玩具，在寶寶面前藏到布或盒下',
      '讓它持續發聲',
      '鼓勵他循聲找出來',
      '找到一起歡呼',
    ],
    followUps: ['他會朝聲音的方向找嗎？'],
    safetyNotes: '玩具無小零件；藏處安全好掀開。',
    endingLine: '找到了！耳朵真靈。',
    minAge: 8,
    maxAge: 14,
    required: [],
    optional: [],
    zpd: ['objectPermanence'],
    focus: ['social_cognitive', 'language'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '疊高推倒囉',
    description: '一起把軟積木疊高再推倒，體驗建構與因果、釋放情緒。',
    openingLine: '疊高高……推倒囉，嘩！',
    steps: ['用軟積木或杯子疊一座小塔', '邀寶寶一起放上去', '數到三一起推倒', '笑完再疊一次'],
    followUps: ['他比較愛疊還是推倒？'],
    safetyNotes: '積木柔軟無小零件；在軟墊區進行。',
    endingLine: '疊了又倒，好好玩！',
    minAge: 9,
    maxAge: 15,
    required: [],
    optional: [],
    zpd: ['canPincerGrip'],
    focus: ['fine_motor', 'social_cognitive'],
    stimulation: 'medium',
    playType: 'parallel',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '拍拍小水盆',
    description: '在淺水盆中拍水、撈玩具，享受觸覺與手部動作（洗澡時也適合）。',
    openingLine: '拍拍水，水花跳起來囉！',
    steps: [
      '在淺水盆放少量溫水與漂浮玩具',
      '讓寶寶坐穩或托好',
      '鼓勵他拍水、撈玩具',
      '描述「拍拍、嘩啦」',
    ],
    followUps: ['他喜歡拍水的感覺嗎？'],
    safetyNotes: '⚠️ 戲水全程一手托穩、絕不可單獨留置；水位極淺、地面防滑、玩後立即清空。',
    endingLine: '玩水好開心，擦乾手手。',
    minAge: 8,
    maxAge: 15,
    required: [],
    optional: [],
    zpd: [],
    focus: ['fine_motor', 'emotional'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: false,
    companionType: 'sensory',
    fallback: false,
  },
  {
    title: '唸謠拍手手',
    description: '配合節奏唸童謠並做手部動作，連結語言、節奏與模仿。',
    openingLine: '我們來唸謠：「拍拍手，點點頭」～',
    steps: ['選一首短童謠', '邊唸邊做拍手、點頭等動作', '在重複處停頓等他接', '反覆同一首加深記憶'],
    followUps: ['他會跟著做哪個動作？'],
    safetyNotes: null,
    endingLine: '唸謠好好玩，再來一次。',
    minAge: 8,
    maxAge: 15,
    required: [],
    optional: [],
    zpd: ['imitatesActions'],
    focus: ['language', 'social_cognitive'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'music',
    fallback: false,
  },
  {
    title: '說說你的心情',
    description: '在寶寶有情緒時溫柔命名感受，幫助情緒理解與共調。',
    openingLine: '你看起來有點難過，馬麻/把拔懂～',
    steps: [
      '蹲下與寶寶平視',
      '溫柔說出他的情緒：「你生氣了」「有點怕怕」',
      '抱抱或拍拍給予安撫',
      '等他平靜再轉移注意',
    ],
    followUps: ['什麼最能安撫他？'],
    safetyNotes: '若持續哭鬧不安，先排除餓了/尿布/不適/生病。',
    endingLine: '情緒過去了，我們沒事了。',
    minAge: 8,
    maxAge: 18,
    required: [],
    optional: [],
    zpd: ['selfSoothing'],
    focus: ['emotional'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'calm_down',
    fallback: false,
  },
  {
    title: '安撫小被被',
    description: '清醒時用固定的安撫物與擁抱，建立安全感與分離安心。',
    openingLine: '抱著你的小被被，馬麻/把拔在這裡。',
    steps: [
      '清醒陪伴時給他固定的安撫物',
      '一起抱著、輕拍',
      '溫柔說「馬麻/把拔等一下就回來」',
      '短暫離開再回來建立信任',
    ],
    followUps: ['有安撫物他比較安心嗎？'],
    safetyNotes: '⚠️ 未滿 1 歲睡眠時嬰兒床須淨空，安撫物僅在「清醒且有人陪」時使用。',
    endingLine: '有小被被陪你，好安心。',
    minAge: 9,
    maxAge: 18,
    required: [],
    optional: [],
    zpd: ['selfSoothing'],
    focus: ['emotional'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'calm_down',
    fallback: false,
  },
  {
    title: '推推滾筒走',
    description: '讓扶站的寶寶推穩固的箱子或學步推車，練習往前邁步。',
    openingLine: '推著它，一步一步往前走～',
    steps: [
      '給寶寶一個夠重、穩固、好握的推具',
      '讓他扶著站好',
      '鼓勵他邊推邊往前邁步',
      '在旁保護控制速度',
    ],
    followUps: ['他推著能走幾步？'],
    safetyNotes: '推具需穩重不易翻、地面平整淨空、全程在旁保護避免暴衝。',
    endingLine: '推著走好棒，越來越穩了！',
    minAge: 10,
    maxAge: 16,
    required: ['canPullToStand'],
    optional: [],
    zpd: ['canWalkIndependently'],
    focus: ['gross_motor'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: false,
    companionType: 'play',
    fallback: false,
  },
]
