// 內容批次：36–60 個月（PRESCHOOLER 36–48m + PRESCHOOLER_PLUS 48–60m）共 30 條。
// 里程碑：單腳跳、用剪刀、畫人、描述事件、合作遊戲、遵守規則、寫名字、來回對話。
// 全部可安全在家、需成人看顧；工具/移動類標安全註記並排除睡前/生病日。非醫療內容。

export const activities = [
  // ===================== PRESCHOOLER 36–48m =====================
  {
    title: '單腳站站看',
    description: '練習單腳站立與單腳跳，發展平衡與下肢控制。',
    openingLine: '像金雞一樣，單腳站站看，幾秒不倒？',
    steps: ['示範單腳站、數秒', '牽手陪他試一次', '放手讓他自己站', '再挑戰單腳小跳'],
    followUps: ['他單腳能站幾秒？'],
    safetyNotes: '地面防滑、周圍淨空、在旁保護。',
    endingLine: '平衡感真棒，金雞獨立成功！',
    minAge: 36,
    maxAge: 54,
    required: ['canRun'],
    optional: [],
    zpd: ['canHopOneFoot'],
    focus: ['gross_motor'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '安全剪刀剪一剪',
    description: '用兒童安全剪刀剪紙，練習雙手協調與工具使用。',
    openingLine: '我們用小剪刀，沿著線剪剪看～',
    steps: ['給兒童安全剪刀與畫線的紙', '示範正確握法與開合', '陪他沿粗線剪', '剪下的紙拼成圖案'],
    followUps: ['他能沿線剪了嗎？'],
    safetyNotes: '⚠️ 只用圓頭兒童安全剪刀、全程在旁監督、用畢立即收好。',
    endingLine: '剪得真好，小手好靈巧！',
    minAge: 36,
    maxAge: 54,
    required: [],
    optional: [],
    zpd: ['canUseScissors'],
    focus: ['fine_motor'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'kitchen',
    minDur: 5,
    maxDur: 15,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'creative',
    fallback: false,
  },
  {
    title: '畫一個人',
    description: '引導孩子畫出有頭、身體、手腳的人，發展表徵繪畫。',
    openingLine: '我們來畫一個人，先畫圓圓的頭～',
    steps: ['示範畫頭、身體、手腳', '請他加上眼睛嘴巴', '讓他畫自己的版本', '一起說畫了誰'],
    followUps: ['他畫的人有幾個部位？'],
    safetyNotes: '用無毒可水洗筆。',
    endingLine: '畫得好棒，是誰呀？',
    minAge: 36,
    maxAge: 54,
    required: [],
    optional: [],
    zpd: ['canDrawCircle'],
    focus: ['fine_motor', 'social_cognitive'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 5,
    maxDur: 15,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'creative',
    fallback: false,
  },
  {
    title: '說一件好玩的事',
    description: '請孩子描述今天做了什麼，練習敘事與時間順序。',
    openingLine: '今天有什麼好玩的事？說給我聽～',
    steps: ['問一個開放問題', '用「然後呢」引導他繼續', '幫他補上時間順序詞', '專心聽並回應'],
    followUps: ['他能說出事情的先後嗎？'],
    safetyNotes: null,
    endingLine: '說得好清楚，真會講！',
    minAge: 36,
    maxAge: 54,
    required: [],
    optional: [],
    zpd: ['canDescribeEvents'],
    focus: ['language'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'talk',
    fallback: false,
  },
  {
    title: '合作蓋城堡',
    description: '一起用積木合力蓋一座城堡，練習合作、分工與協商。',
    openingLine: '我們一起蓋一座大城堡，你負責這邊！',
    steps: ['一起決定要蓋什麼', '分工各自負責一部分', '討論怎麼接起來', '完成一起欣賞'],
    followUps: ['你們怎麼分工的？'],
    safetyNotes: '積木無小零件、注意倒塌方向。',
    endingLine: '合作蓋得好棒，團隊真厲害！',
    minAge: 36,
    maxAge: 56,
    required: [],
    optional: [],
    zpd: ['cooperativePlay'],
    focus: ['social_cognitive'],
    stimulation: 'low',
    playType: 'cooperative',
    resources: [],
    space: 'living_room',
    minDur: 6,
    maxDur: 18,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '角色扮演遊戲',
    description: '扮演老師、消防員、爸媽等角色演短劇，發展想像與社會理解。',
    openingLine: '今天你想當誰呢？我們來演一場！',
    steps: ['一起選角色與情境', '用道具或服裝裝扮', '即興演出小情節', '互換角色再演'],
    followUps: ['他最愛扮演什麼角色？'],
    safetyNotes: '道具安全、無小零件與尖角。',
    endingLine: '演得好精彩，小演員！',
    minAge: 36,
    maxAge: 60,
    required: [],
    optional: [],
    zpd: ['cooperativePlay'],
    focus: ['social_cognitive', 'language'],
    stimulation: 'medium',
    playType: 'cooperative',
    resources: [],
    space: 'anywhere',
    minDur: 6,
    maxDur: 18,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'creative',
    fallback: false,
  },
  {
    title: '跳圈圈',
    description: '在地上排圈圈讓孩子雙腳或單腳跳進跳出，練習跳躍與協調。',
    openingLine: '一個圈一個圈，跳進去，跳！',
    steps: ['用呼拉圈或膠帶排幾個圈', '示範雙腳跳進每個圈', '挑戰單腳跳', '加快或變化路線'],
    followUps: ['他能連跳幾個圈？'],
    safetyNotes: '地面防滑、圈固定不滑、在旁保護。',
    endingLine: '跳得又快又穩，好厲害！',
    minAge: 38,
    maxAge: 58,
    required: ['canJumpBothFeet'],
    optional: [],
    zpd: ['canHopOneFoot'],
    focus: ['gross_motor'],
    stimulation: 'high',
    playType: 'solitary',
    resources: [],
    space: 'outdoor',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: false,
    companionType: 'outdoor',
    fallback: false,
  },
  {
    title: '數量配對 1 到 5',
    description: '把數字與對應數量的物品配對，建立數與量的連結。',
    openingLine: '數字 3 要配幾個積木呢？來數數～',
    steps: ['排出數字卡 1–5', '請他放對應數量的物品', '一起點數確認', '逐步增加難度'],
    followUps: ['他能配對到幾？'],
    safetyNotes: '物件無小零件。',
    endingLine: '數量配對全對，數學小高手！',
    minAge: 38,
    maxAge: 58,
    required: [],
    optional: [],
    zpd: [],
    focus: ['social_cognitive', 'language'],
    stimulation: 'low',
    playType: 'cooperative',
    resources: [],
    space: 'anywhere',
    minDur: 5,
    maxDur: 15,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '走平衡木',
    description: '在地上的板子或膠帶線上練習穩定行走與轉身。',
    openingLine: '張開手，走過獨木橋，別掉下河喔～',
    steps: ['用矮板或膠帶當平衡木', '示範張手慢走', '陪他走一次', '挑戰倒退或轉身'],
    followUps: ['他能走到底不掉嗎？'],
    safetyNotes: '板子貼地穩固、周圍鋪軟墊、在旁保護。',
    endingLine: '平衡感真好，過橋成功！',
    minAge: 36,
    maxAge: 56,
    required: ['canWalkIndependently'],
    optional: [],
    zpd: [],
    focus: ['gross_motor'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'living_room',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: false,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '撕貼拼貼畫',
    description: '撕色紙拼貼成圖案，練習手部控制、構圖與創意。',
    openingLine: '撕一撕、貼一貼，拼出一幅畫！',
    steps: ['準備色紙與膠水', '示範撕成小片貼出形狀', '讓他自由拼貼', '一起命名作品'],
    followUps: ['他拼出什麼圖？'],
    safetyNotes: '膠水無毒、全程看顧；用畢洗手。',
    endingLine: '拼貼好有創意，貼牆上展示！',
    minAge: 36,
    maxAge: 56,
    required: [],
    optional: [],
    zpd: [],
    focus: ['fine_motor', 'social_cognitive'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'kitchen',
    minDur: 6,
    maxDur: 18,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'creative',
    fallback: false,
  },
  {
    title: '情緒怎麼解決',
    description: '用情境討論「如果生氣／難過可以怎麼辦」，建立情緒因應策略。',
    openingLine: '如果玩具被搶走，我們可以怎麼辦呢？',
    steps: ['提出一個常見情緒情境', '問他「可以怎麼做」', '一起想出幾種方法', '練習說出來或演一遍'],
    followUps: ['他想到哪些好方法？'],
    safetyNotes: null,
    endingLine: '你想到好多辦法，真棒！',
    minAge: 36,
    maxAge: 60,
    required: [],
    optional: [],
    zpd: ['toleratesFrustration'],
    focus: ['emotional', 'social_cognitive'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'talk',
    fallback: false,
  },
  {
    title: '顏色混合魔法',
    description: '用顏料混色觀察變化，認識顏色並培養好奇與觀察。',
    openingLine: '紅色加黃色，會變成什麼顏色呢？',
    steps: ['準備紅黃藍可水洗顏料', '示範兩色相混', '請他猜會變什麼色', '一起記錄新顏色'],
    followUps: ['他發現哪些新顏色？'],
    safetyNotes: '顏料無毒可水洗、全程看顧避免入口；鋪好桌面。',
    endingLine: '變出新顏色了，好神奇！',
    minAge: 38,
    maxAge: 58,
    required: [],
    optional: [],
    zpd: [],
    focus: ['fine_motor', 'social_cognitive'],
    stimulation: 'low',
    playType: 'cooperative',
    resources: [],
    space: 'kitchen',
    minDur: 6,
    maxDur: 18,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'creative',
    fallback: false,
  },

  // ===================== PRESCHOOLER_PLUS 48–60m =====================
  {
    title: '練習寫筆畫',
    description: '描寫直線、橫線、圓等基本筆畫，為寫字打基礎。',
    openingLine: '跟著虛線描描看，一筆一畫慢慢來～',
    steps: ['準備有虛線筆畫的紙', '示範正確握筆描寫', '陪他描幾筆', '進階描自己名字的第一個字'],
    followUps: ['他握筆穩了嗎？'],
    safetyNotes: '用無毒筆、注意握筆姿勢不過度用力。',
    endingLine: '寫得真認真，越來越棒！',
    minAge: 48,
    maxAge: 60,
    required: [],
    optional: [],
    zpd: ['canWriteName'],
    focus: ['fine_motor'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 5,
    maxDur: 15,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'creative',
    fallback: false,
  },
  {
    title: '你問我答',
    description: '輪流問答（喜歡什麼、為什麼），練習來回對話與表達理由。',
    openingLine: '我問你答，再換你問我，準備好了嗎？',
    steps: ['輪流問對方問題', '鼓勵他回答並說原因', '追問「為什麼呢」', '互換主導'],
    followUps: ['他能說出理由嗎？'],
    safetyNotes: null,
    endingLine: '聊得真好，你好會表達！',
    minAge: 48,
    maxAge: 60,
    required: [],
    optional: [],
    zpd: ['canHaveConversation'],
    focus: ['language', 'social_cognitive'],
    stimulation: 'low',
    playType: 'cooperative',
    resources: [],
    space: 'anywhere',
    minDur: 5,
    maxDur: 15,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'talk',
    fallback: false,
  },
  {
    title: '一起玩桌遊',
    description: '玩簡單的擲骰／配對桌遊，練習遵守規則、輪流與輸贏情緒。',
    openingLine: '我們來玩桌遊，輪流擲骰子，要守規則喔～',
    steps: ['選一個簡單規則的桌遊', '一起讀規則', '輪流進行', '討論輸贏時的心情'],
    followUps: ['他能接受輸的結果嗎？'],
    safetyNotes: '配件無小零件（或全程監督）。',
    endingLine: '玩得好開心，規則都守住了！',
    minAge: 48,
    maxAge: 60,
    required: [],
    optional: [],
    zpd: ['canFollowRules', 'cooperativePlay'],
    focus: ['social_cognitive', 'emotional'],
    stimulation: 'low',
    playType: 'cooperative',
    resources: [],
    space: 'anywhere',
    minDur: 6,
    maxDur: 20,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '闖關小任務',
    description: '設計幾個步驟的小任務一起完成，練習合作、計畫與堅持。',
    openingLine: '今天有三個小任務，我們一起闖關吧！',
    steps: ['一起設定 2–3 個關卡任務', '分工或合作完成', '每完成一關擊掌', '全部完成給獎勵'],
    followUps: ['哪一關最有挑戰？'],
    safetyNotes: '任務內容安全、避免危險動作。',
    endingLine: '全部闖關成功，超強團隊！',
    minAge: 48,
    maxAge: 60,
    required: [],
    optional: [],
    zpd: ['cooperativePlay'],
    focus: ['social_cognitive', 'emotional'],
    stimulation: 'medium',
    playType: 'cooperative',
    resources: [],
    space: 'anywhere',
    minDur: 8,
    maxDur: 20,
    bedtimeSafe: false,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '拍球接球',
    description: '練習拍球、丟接球，發展手眼協調與反應。',
    openingLine: '球丟給你，接住！再丟回來～',
    steps: ['用適中大小的球', '近距離互相丟接', '練習拍球落地反彈', '拉開距離增加挑戰'],
    followUps: ['他能連續接幾次？'],
    safetyNotes: '球軟硬適中、場地淨空、避免衝撞。',
    endingLine: '接得真準，球技進步了！',
    minAge: 48,
    maxAge: 60,
    required: ['canRun'],
    optional: [],
    zpd: ['canHopOneFoot'],
    focus: ['gross_motor'],
    stimulation: 'high',
    playType: 'cooperative',
    resources: [],
    space: 'outdoor',
    minDur: 5,
    maxDur: 15,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: false,
    companionType: 'outdoor',
    fallback: false,
  },
  {
    title: '數到十與加一',
    description: '數到 10、玩「再加一個是幾」，建立基礎數感與加法概念。',
    openingLine: '三個再加一個，變成幾個呢？',
    steps: ['用實物數到 10', '玩「再加一個」', '玩「拿走一個」', '逐步用口頭計算'],
    followUps: ['他能算加一減一嗎？'],
    safetyNotes: '物件無小零件。',
    endingLine: '算得好快，數學小達人！',
    minAge: 48,
    maxAge: 60,
    required: [],
    optional: [],
    zpd: [],
    focus: ['social_cognitive', 'language'],
    stimulation: 'low',
    playType: 'cooperative',
    resources: [],
    space: 'anywhere',
    minDur: 5,
    maxDur: 15,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'talk',
    fallback: false,
  },
  {
    title: '自己編故事',
    description: '用圖卡或玩偶當提示，請孩子編一個小故事，發展敘事與想像。',
    openingLine: '從前從前……接下來發生什麼事呢？',
    steps: ['給幾張圖卡或玩偶當角色', '起個頭請他接故事', '用問題引導情節發展', '一起說出結局'],
    followUps: ['他編出什麼情節？'],
    safetyNotes: '道具安全無小零件。',
    endingLine: '故事好精彩，你是說故事高手！',
    minAge: 48,
    maxAge: 60,
    required: [],
    optional: [],
    zpd: ['canHaveConversation'],
    focus: ['language'],
    stimulation: 'low',
    playType: 'cooperative',
    resources: [],
    space: 'anywhere',
    minDur: 6,
    maxDur: 18,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'talk',
    fallback: false,
  },
  {
    title: '摺紙小手作',
    description: '一起摺簡單的紙飛機、紙船，練習對邊對齊與步驟跟隨。',
    openingLine: '我們來摺紙飛機，照步驟一起摺～',
    steps: ['準備正方或長方紙', '示範一步步摺、壓平', '陪他對齊邊角', '完成後試飛或玩'],
    followUps: ['他能跟著步驟摺嗎？'],
    safetyNotes: '紙張邊緣注意割傷；作品玩耍時注意安全。',
    endingLine: '摺得好棒，飛機飛得真遠！',
    minAge: 48,
    maxAge: 60,
    required: [],
    optional: [],
    zpd: ['canUseScissors'],
    focus: ['fine_motor', 'social_cognitive'],
    stimulation: 'low',
    playType: 'cooperative',
    resources: [],
    space: 'anywhere',
    minDur: 6,
    maxDur: 18,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'creative',
    fallback: false,
  },
  {
    title: '分類整理玩具',
    description: '把玩具依類別／顏色分類收納，練習邏輯分類與物歸原位。',
    openingLine: '我們來當整理達人，把玩具分類收好～',
    steps: ['決定分類方式（類別或顏色）', '一起把玩具分堆', '放進對應的箱子', '完成欣賞整齊的成果'],
    followUps: ['他想到什麼分類方法？'],
    safetyNotes: null,
    endingLine: '整理得好整齊，真厲害！',
    minAge: 42,
    maxAge: 60,
    required: [],
    optional: [],
    zpd: [],
    focus: ['social_cognitive', 'emotional'],
    stimulation: 'low',
    playType: 'cooperative',
    resources: [],
    space: 'anywhere',
    minDur: 5,
    maxDur: 15,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '小小幫廚',
    description: '一起做免火簡單點心（洗水果、拌沙拉），練習手部技巧與合作。',
    openingLine: '今天當小幫廚，我們一起做點心！',
    steps: ['挑免火安全的步驟（洗、拌、擺盤）', '示範並陪他做', '一起完成擺盤', '開心享用成果'],
    followUps: ['他最喜歡哪個步驟？'],
    safetyNotes: '⚠️ 避開刀具、熱源與生食風險；全程監督、做前後洗手。',
    endingLine: '小幫廚太棒了，好好吃！',
    minAge: 42,
    maxAge: 60,
    required: [],
    optional: [],
    zpd: ['cooperativePlay'],
    focus: ['fine_motor', 'social_cognitive'],
    stimulation: 'low',
    playType: 'cooperative',
    resources: [],
    space: 'kitchen',
    minDur: 8,
    maxDur: 20,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'creative',
    fallback: false,
  },
  {
    title: '認字找一找',
    description: '在書或招牌上找認得的字／注音，培養文字覺察與閱讀興趣。',
    openingLine: '看看這頁，有沒有你認得的字？',
    steps: ['翻開繪本或看生活中的字', '指出一個常見字示範', '請他找出相同的字', '唸出來一起認'],
    followUps: ['他認得哪些字了？'],
    safetyNotes: null,
    endingLine: '認得好多字，快變小讀者了！',
    minAge: 48,
    maxAge: 60,
    required: [],
    optional: [],
    zpd: ['canHaveConversation'],
    focus: ['language'],
    stimulation: 'low',
    playType: 'cooperative',
    resources: [],
    space: 'anywhere',
    minDur: 5,
    maxDur: 15,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'read',
    fallback: false,
  },
  {
    title: '睡前聊聊明天',
    description: '睡前一起說說明天想做的事，練習計畫表達與安定情緒。',
    openingLine: '躺好，我們聊聊明天想做什麼呢？',
    steps: ['調暗燈光躺好', '輪流說明天的一個計畫', '一起想像那個畫面', '溫柔晚安收尾'],
    followUps: ['他期待明天的什麼？'],
    safetyNotes: null,
    endingLine: '期待明天，先好好睡覺，晚安。',
    minAge: 42,
    maxAge: 60,
    required: [],
    optional: [],
    zpd: ['canHaveConversation'],
    focus: ['emotional', 'language'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'bedroom',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'calm_down',
    fallback: false,
  },
]
