// 內容批次：24–36 個月（TODDLER_PLAYER）共 24 條。
// 里程碑：跑跳、畫圓、完整句子、假扮複雜化、輪流合作、承受挫折、數量/大小概念。
// 全部可安全在家、需成人看顧；移動類標安全註記並排除睡前/生病日。非醫療內容。

export const activities = [
  {
    title: '學青蛙跳',
    description: '蹲下雙腳一起往前跳，練習雙腳跳與下肢爆發力。',
    openingLine: '我們來學青蛙，呱呱跳跳跳！',
    steps: ['示範蹲下雙腳一起跳', '牽手帶他一起跳', '放手讓他自己跳', '比比看跳多遠'],
    followUps: ['他能雙腳同時離地嗎？'],
    safetyNotes: '在軟墊或淨空平地、在旁保護避免跌坐。',
    endingLine: '跳得真高，小青蛙好棒！',
    minAge: 24,
    maxAge: 36,
    required: ['canRun'],
    optional: [],
    zpd: ['canJumpBothFeet'],
    focus: ['gross_motor'],
    stimulation: 'high',
    playType: 'parallel',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: false,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '畫圈圈',
    description: '示範畫圓，鼓勵孩子嘗試畫出封閉的圈，練習運筆控制。',
    openingLine: '我們來畫圈圈，繞一圈接起來～',
    steps: ['示範慢慢畫一個圓', '牽他的手畫一次', '讓他自己試', '把圓變成太陽或臉'],
    followUps: ['他畫的圈接起來了嗎？'],
    safetyNotes: '用無毒可水洗筆。',
    endingLine: '畫圈圈好棒，變成笑臉了！',
    minAge: 28,
    maxAge: 40,
    required: [],
    optional: [],
    zpd: ['canDrawCircle'],
    focus: ['fine_motor'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'creative',
    fallback: false,
  },
  {
    title: '說完整的話',
    description: '把孩子的短句擴成完整句子示範，鼓勵用三四個字表達。',
    openingLine: '你說「要餅乾」，我們說「我要吃餅乾」！',
    steps: ['聽孩子表達需求', '示範擴成完整句子', '鼓勵他跟著說一次', '生活中持續示範'],
    followUps: ['他開始說較長的句子了嗎？'],
    safetyNotes: null,
    endingLine: '說得好完整，越來越會講了！',
    minAge: 28,
    maxAge: 42,
    required: [],
    optional: [],
    zpd: ['usesSentences'],
    focus: ['language'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'talk',
    fallback: false,
  },
  {
    title: '假扮看醫生',
    description: '輪流當醫生與病人，用玩具聽診器假扮看診，發展假扮與同理。',
    openingLine: '醫生你好，我肚子痛痛，幫我看看～',
    steps: ['準備玩具醫生組', '輪流當醫生與病人', '假裝聽診、打針、安慰', '互換角色再玩'],
    followUps: ['他演醫生時說了什麼？'],
    safetyNotes: '玩具無小零件、無尖角。',
    endingLine: '謝謝小醫生，我好多了！',
    minAge: 24,
    maxAge: 42,
    required: [],
    optional: [],
    zpd: ['symbolicPlay'],
    focus: ['social_cognitive', 'language'],
    stimulation: 'low',
    playType: 'cooperative',
    resources: [],
    space: 'anywhere',
    minDur: 5,
    maxDur: 15,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'creative',
    fallback: false,
  },
  {
    title: '走直線平衡',
    description: '沿地上的線或膠帶走，練習平衡與身體控制。',
    openingLine: '走在線上不要掉下去，慢慢走～',
    steps: ['在地上貼一條直線', '示範張開手走線', '牽手陪他走一次', '讓他自己挑戰'],
    followUps: ['他能走幾步不偏離？'],
    safetyNotes: '地面防滑、周圍淨空、在旁保護。',
    endingLine: '平衡感真好，走得好穩！',
    minAge: 24,
    maxAge: 40,
    required: ['canWalkIndependently'],
    optional: [],
    zpd: [],
    focus: ['gross_motor'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '串大珠子',
    description: '把大珠子串到繩子上，練習雙手協調與專注。',
    openingLine: '一顆一顆穿起來，做條漂亮項鍊！',
    steps: ['給大珠子與硬頭粗繩', '示範穿一顆', '讓他自己穿', '數數穿了幾顆'],
    followUps: ['他能自己穿過洞嗎？'],
    safetyNotes: '珠子需大於口腔、無法吞食；繩子短、全程看顧避免纏繞。',
    endingLine: '項鍊好美，你好厲害！',
    minAge: 26,
    maxAge: 42,
    required: [],
    optional: [],
    zpd: ['canPincerGrip'],
    focus: ['fine_motor'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 5,
    maxDur: 15,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'creative',
    fallback: false,
  },
  {
    title: '數數一二三',
    description: '一起數樓梯、點心、玩具，建立數字與數量的連結。',
    openingLine: '我們來數數看，有幾個呀？一、二、三～',
    steps: ['指著物品一個個數', '請孩子跟著數', '問「總共幾個」', '在生活中常常數'],
    followUps: ['他能數到幾？'],
    safetyNotes: null,
    endingLine: '數得真好，你會數數了！',
    minAge: 24,
    maxAge: 40,
    required: [],
    optional: [],
    zpd: [],
    focus: ['social_cognitive', 'language'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'talk',
    fallback: false,
  },
  {
    title: '黏土搓搓捏捏',
    description: '搓圓、壓扁、捏形狀，強化手部肌肉與創造力。',
    openingLine: '黏土軟軟的，我們來捏小東西！',
    steps: ['給安全無毒黏土', '示範搓圓、壓扁、搓長條', '讓他自由創作', '一起說做了什麼'],
    followUps: ['他做出什麼作品？'],
    safetyNotes: '用無毒黏土、全程看顧避免入口；玩後洗手。',
    endingLine: '捏得好有創意，真棒！',
    minAge: 24,
    maxAge: 42,
    required: [],
    optional: [],
    zpd: [],
    focus: ['fine_motor'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'kitchen',
    minDur: 5,
    maxDur: 15,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'creative',
    fallback: false,
  },
  {
    title: '躲貓貓數到十',
    description: '一人躲、一人數到十再找，練習數數、輪流與大動作。',
    openingLine: '我數到十，你快去躲，準備好囉！',
    steps: ['約定安全的躲藏範圍', '一人遮眼數到十', '另一人躲起來', '找到後互換角色'],
    followUps: ['他會找哪些地方躲？'],
    safetyNotes: '限定安全範圍、移開危險物、避免躲進密閉空間。',
    endingLine: '找到你了，玩得好開心！',
    minAge: 28,
    maxAge: 44,
    required: ['canRun'],
    optional: [],
    zpd: ['canTakeTurns'],
    focus: ['gross_motor', 'social_cognitive'],
    stimulation: 'high',
    playType: 'cooperative',
    resources: [],
    space: 'anywhere',
    minDur: 5,
    maxDur: 15,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: false,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '假扮小商店',
    description: '擺出商品玩買賣，輪流當老闆與客人，發展語言、數量與社交。',
    openingLine: '歡迎光臨！你想買什麼呢？',
    steps: ['擺出玩具或安全物品當商品', '輪流當老闆與客人', '假裝付錢、找錢、道謝', '互換角色'],
    followUps: ['他會說哪些買賣對話？'],
    safetyNotes: '道具無小零件。',
    endingLine: '謝謝光臨，歡迎下次再來！',
    minAge: 28,
    maxAge: 44,
    required: [],
    optional: [],
    zpd: ['usesSentences', 'symbolicPlay'],
    focus: ['social_cognitive', 'language'],
    stimulation: 'low',
    playType: 'cooperative',
    resources: [],
    space: 'anywhere',
    minDur: 5,
    maxDur: 15,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'creative',
    fallback: false,
  },
  {
    title: '生氣了怎麼辦',
    description: '在孩子受挫時陪他命名情緒、練習深呼吸與簡單因應。',
    openingLine: '你很生氣對不對？我們一起深呼吸～',
    steps: [
      '蹲下與孩子平視、接納情緒',
      '幫他說出「你很生氣／失望」',
      '一起做三次深呼吸',
      '冷靜後討論怎麼辦',
    ],
    followUps: ['什麼方法最能幫他冷靜？'],
    safetyNotes: '先確保安全；情緒激烈時先陪伴不說教。',
    endingLine: '情緒過去了，你做得很好。',
    minAge: 24,
    maxAge: 48,
    required: [],
    optional: [],
    zpd: ['toleratesFrustration'],
    focus: ['emotional'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'calm_down',
    fallback: false,
  },
  {
    title: '唱跳律動',
    description: '跟著音樂做動作律動，練習節奏感、協調與模仿。',
    openingLine: '音樂來囉，我們一起扭一扭、跳一跳！',
    steps: ['放輕快的兒歌', '示範拍手、轉圈、踏步', '讓孩子跟著做', '自由發揮自己的舞步'],
    followUps: ['他最愛哪個動作？'],
    safetyNotes: '場地淨空防滑、避免過度興奮跌倒。',
    endingLine: '跳得真好，小舞星！',
    minAge: 24,
    maxAge: 44,
    required: ['canWalkIndependently'],
    optional: [],
    zpd: [],
    focus: ['gross_motor', 'social_cognitive'],
    stimulation: 'high',
    playType: 'parallel',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 12,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: true,
    companionType: 'music',
    fallback: false,
  },
  {
    title: '大中小排排看',
    description: '把同類物品依大小排序，建立大小與序列概念。',
    openingLine: '哪個最大？哪個最小？排排看～',
    steps: ['拿三個大小不同的同類物', '示範由大到小排', '讓他自己排', '說「大、中、小」'],
    followUps: ['他能正確排序嗎？'],
    safetyNotes: '物件大於口腔、無小零件。',
    endingLine: '排得真整齊，好聰明！',
    minAge: 26,
    maxAge: 42,
    required: [],
    optional: [],
    zpd: [],
    focus: ['social_cognitive', 'fine_motor'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '倒水玩一玩',
    description: '在容器間倒水，練習手腕控制、專注與容量概念。',
    openingLine: '把水倒過去，不要灑出來喔～',
    steps: ['準備兩個杯子與少量水', '示範慢慢倒', '讓他練習倒來倒去', '描述「滿了、空了」'],
    followUps: ['他倒得越來越穩嗎？'],
    safetyNotes: '少量水、地面防滑、避免滑倒；全程看顧。',
    endingLine: '倒得好穩，手好巧！',
    minAge: 26,
    maxAge: 42,
    required: [],
    optional: [],
    zpd: [],
    focus: ['fine_motor', 'social_cognitive'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'kitchen',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'sensory',
    fallback: false,
  },
  {
    title: '聽指令做動作',
    description: '說「摸摸頭」「拍拍手」讓孩子照做，練習聽理解與身體控制。',
    openingLine: '聽我說，摸摸頭！再來，拍拍手！',
    steps: ['給一個簡單指令', '孩子照做就稱讚', '加入兩步指令「先跳再轉圈」', '輪流由孩子當指揮'],
    followUps: ['他能記得兩步指令嗎？'],
    safetyNotes: '動作幅度安全、場地淨空。',
    endingLine: '都聽懂了，反應好快！',
    minAge: 24,
    maxAge: 42,
    required: [],
    optional: [],
    zpd: [],
    focus: ['language', 'gross_motor'],
    stimulation: 'medium',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '滾球保齡球',
    description: '排好寶特瓶當球瓶，滾球撞倒，練習瞄準與因果。',
    openingLine: '瞄準球瓶，把它們通通滾倒！',
    steps: ['用空寶特瓶排成球瓶', '示範滾球撞倒', '讓孩子試著瞄準', '數數倒了幾瓶'],
    followUps: ['他一次撞倒幾瓶？'],
    safetyNotes: '瓶子輕空、球柔軟、場地淨空。',
    endingLine: '全倒！保齡球高手！',
    minAge: 26,
    maxAge: 44,
    required: [],
    optional: [],
    zpd: [],
    focus: ['gross_motor', 'social_cognitive'],
    stimulation: 'medium',
    playType: 'cooperative',
    resources: [],
    space: 'living_room',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: false,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '蓋印章作畫',
    description: '用印章或蔬果切面沾顏料蓋印，練習手部控制與創意。',
    openingLine: '蓋一個、蓋一個，變出一幅畫！',
    steps: ['準備安全印章與可水洗顏料', '示範沾色蓋印', '讓他自由蓋出圖案', '一起欣賞作品'],
    followUps: ['他蓋出什麼圖案？'],
    safetyNotes: '顏料無毒可水洗、全程看顧避免入口；鋪好桌面。',
    endingLine: '蓋印畫好美，展示起來！',
    minAge: 26,
    maxAge: 44,
    required: [],
    optional: [],
    zpd: [],
    focus: ['fine_motor'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'kitchen',
    minDur: 5,
    maxDur: 15,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'creative',
    fallback: false,
  },
  {
    title: '紅綠燈走走停',
    description: '喊「綠燈走、紅燈停」讓孩子跑動與急停，練習聽指令與自我控制。',
    openingLine: '綠燈走～紅燈，停！',
    steps: ['說明綠燈走、紅燈停', '喊綠燈讓他走或跑', '突然喊紅燈要立刻停', '互換當紅綠燈'],
    followUps: ['他能聽到紅燈馬上停嗎？'],
    safetyNotes: '場地淨空防滑、控制速度避免衝撞。',
    endingLine: '反應好快，紅燈都停得住！',
    minAge: 28,
    maxAge: 46,
    required: ['canRun'],
    optional: [],
    zpd: ['toleratesFrustration'],
    focus: ['gross_motor', 'social_cognitive'],
    stimulation: 'high',
    playType: 'cooperative',
    resources: [],
    space: 'outdoor',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: false,
    companionType: 'outdoor',
    fallback: false,
  },
  {
    title: '我是小幫手',
    description: '邀孩子幫忙簡單家事（擦桌、放餐具），培養責任與成就感。',
    openingLine: '你願意當小幫手嗎？我們一起擦桌子！',
    steps: ['挑一件安全的小家事', '示範怎麼做', '陪他一起完成', '完成後具體稱讚'],
    followUps: ['他喜歡幫哪件忙？'],
    safetyNotes: '挑安全任務、避開刀具熱源與清潔劑。',
    endingLine: '謝謝小幫手，幫了大忙！',
    minAge: 24,
    maxAge: 48,
    required: [],
    optional: [],
    zpd: [],
    focus: ['social_cognitive', 'emotional'],
    stimulation: 'low',
    playType: 'cooperative',
    resources: [],
    space: 'kitchen',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '動物配對卡',
    description: '把相同的動物卡配成一對，練習觀察、記憶與配對。',
    openingLine: '找找看，哪兩張是一樣的動物？',
    steps: ['準備幾組成對的圖卡', '翻開示範找一對', '讓他找出相同的', '說出動物名稱'],
    followUps: ['他配對得越來越快嗎？'],
    safetyNotes: '卡片邊角圓鈍。',
    endingLine: '配對成功，記性真好！',
    minAge: 26,
    maxAge: 44,
    required: [],
    optional: [],
    zpd: [],
    focus: ['social_cognitive', 'language'],
    stimulation: 'low',
    playType: 'cooperative',
    resources: [],
    space: 'anywhere',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '畫畫說故事',
    description: '邊塗鴉邊請孩子說「這是什麼」，連結圖畫與口語敘事。',
    openingLine: '你畫的是什麼呀？說給我聽～',
    steps: ['一起自由塗鴉', '問他畫的是什麼', '把他的話寫在旁邊唸出來', '串成一個小故事'],
    followUps: ['他編了什麼故事？'],
    safetyNotes: '用無毒可水洗筆。',
    endingLine: '故事好精彩，你是小作家！',
    minAge: 30,
    maxAge: 46,
    required: [],
    optional: [],
    zpd: ['usesSentences'],
    focus: ['language', 'fine_motor'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 5,
    maxDur: 15,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'creative',
    fallback: false,
  },
  {
    title: '形狀尋寶',
    description: '在家找出圓形、方形的東西，結合形狀認知與走動探索。',
    openingLine: '我們來找圓形的東西，看誰先找到！',
    steps: ['指定一個形狀', '一起在家裡找符合的物品', '找到就說出名稱', '換下一個形狀'],
    followUps: ['他找到哪些形狀的東西？'],
    safetyNotes: '避免拿取危險或易碎物品。',
    endingLine: '找到好多形狀，眼力真好！',
    minAge: 28,
    maxAge: 46,
    required: ['canWalkIndependently'],
    optional: [],
    zpd: [],
    focus: ['social_cognitive', 'gross_motor'],
    stimulation: 'medium',
    playType: 'cooperative',
    resources: [],
    space: 'anywhere',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: false,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '睡前三件開心事',
    description: '睡前說出今天三件開心的事，培養正向回顧與表達。',
    openingLine: '躺好，說說今天有哪三件開心的事？',
    steps: ['調暗燈光躺好', '輪流說一件今天開心的事', '一起回想細節', '以溫柔晚安收尾'],
    followUps: ['他記得哪件最開心？'],
    safetyNotes: null,
    endingLine: '今天好棒，晚安做個好夢。',
    minAge: 30,
    maxAge: 54,
    required: [],
    optional: [],
    zpd: ['usesSentences'],
    focus: ['emotional', 'language'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'bedroom',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'calm_down',
    fallback: false,
  },
]
