// 內容批次：0–6 個月（NEWBORN 0–3m + EARLY_INFANT 3–6m）共 30 條。
//
// 設計依據：公開、通用的嬰兒發展里程碑共識（如 CDC/AAP 類衛教方向）——
// 視覺追視、tummy time、serve-and-return 對話、撫觸安撫、抓握、翻身、
// 物體恆存萌芽等。所有活動：可安全在家進行、需成人全程看顧、無小零件窒息風險。
// 非醫療/評估內容，由 App 的免責聲明涵蓋。
//
// 欄位值必須落在 schema 的允許集合內（見 build-seed.mjs 的驗證）：
//   focus ∈ emotional|fine_motor|gross_motor|language|social_cognitive
//   stimulation ∈ low|medium|high
//   playType ∈ solitary|parallel|associative|cooperative
//   space ∈ anywhere|living_room|bedroom|outdoor|kitchen
//   companionType ∈ play|talk|read|outdoor|creative|sensory|music|calm_down
//   capability keys 使用 packages/core capability-keys.ts 的 camelCase 值

export const activities = [
  // ===================== NEWBORN 0–3m =====================
  {
    title: '追視紅球',
    description: '用單一鮮豔物件在寶寶眼前緩慢移動，練習視覺追視與專注。',
    openingLine: '看～紅紅的球，跟著它一起看！',
    steps: [
      '把紅色球或玩具放在寶寶眼前約 25 公分',
      '等他對焦後，緩慢往左移再往右',
      '停一下讓他重新對焦',
      '上下也試一次',
    ],
    followUps: ['他的眼睛跟得上嗎？', '比較喜歡往哪一邊看？'],
    safetyNotes: '抱穩頭頸，動作要慢，避免強光直射眼睛。',
    endingLine: '眼睛追得真好，我們休息一下。',
    minAge: 0,
    maxAge: 4,
    required: [],
    optional: [],
    zpd: [],
    focus: ['social_cognitive'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 2,
    maxDur: 6,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '床邊輕語旁白',
    description: '把正在做的事輕聲說給寶寶聽，建立語言輸入與安全感。',
    openingLine: '馬麻/把拔跟你說說話喔～',
    steps: [
      '抱著或在換尿布時面對寶寶',
      '用溫柔語調描述你在做什麼',
      '說完一句停 2 秒，看他的回應',
      '回應他的咕咕聲再繼續',
    ],
    followUps: ['他發出聲音回應你了嗎？'],
    safetyNotes: null,
    endingLine: '謝謝你聽馬麻/把拔說話。',
    minAge: 0,
    maxAge: 6,
    required: [],
    optional: [],
    zpd: ['meaningfulBabble'],
    focus: ['language'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 2,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'talk',
    fallback: false,
  },
  {
    title: '溫柔撫觸按摩',
    description: '用手掌輕緩按摩四肢與背部，幫助放鬆、促進親子連結。',
    openingLine: '我們來按摩放鬆一下，舒服喔～',
    steps: [
      '在溫暖房間讓寶寶仰躺',
      '雙手搓暖，輕柔地由大腿往腳掌撫摸',
      '再到手臂、肚子畫小圓',
      '邊按邊輕聲說話',
    ],
    followUps: ['他最享受哪個部位？'],
    safetyNotes: '力道輕、避開肚臍未癒處；餵奶後勿立即按摩肚子。哭鬧就停止。',
    endingLine: '全身鬆鬆的，好舒服。',
    minAge: 0,
    maxAge: 6,
    required: [],
    optional: [],
    zpd: ['selfSoothing'],
    focus: ['emotional'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'bedroom',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'calm_down',
    fallback: false,
  },
  {
    title: '腳踏車運動',
    description: '輕握寶寶雙腳做踩腳踏車動作，活動髖關節、舒緩脹氣。',
    openingLine: '腳腳來騎腳踏車，踩踩踩～',
    steps: [
      '寶寶仰躺，輕握雙腳踝',
      '像踩腳踏車一樣交替彎曲',
      '配合節奏唸「踩、踩、踩」',
      '做 30 秒休息一下',
    ],
    followUps: null,
    safetyNotes: '動作輕緩、不強拉關節；剛喝完奶先休息。',
    endingLine: '腳腳運動完囉，真棒。',
    minAge: 0,
    maxAge: 5,
    required: [],
    optional: [],
    zpd: [],
    focus: ['gross_motor'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 2,
    maxDur: 5,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '鏡子裡的寶寶',
    description: '抱著寶寶看安全鏡子，引發對臉孔的興趣與自我覺察萌芽。',
    openingLine: '鏡子裡那個可愛的是誰呀？',
    steps: [
      '抱寶寶面向安全的鏡子',
      '指著鏡中的他說「這是你」',
      '揮揮手、做表情讓他觀察',
      '指你自己說「這是馬麻/把拔」',
    ],
    followUps: ['他盯著鏡子裡的臉看嗎？'],
    safetyNotes: '使用無破損的安全鏡（壓克力或固定式），勿讓寶寶單獨拿。',
    endingLine: '鏡子裡的你最可愛了。',
    minAge: 0,
    maxAge: 6,
    required: [],
    optional: [],
    zpd: [],
    focus: ['social_cognitive'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 2,
    maxDur: 6,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '抓握小搖鈴',
    description: '把柔軟搖鈴放進寶寶掌心，誘發抓握反射與手部覺察。',
    openingLine: '握握看，這個會發出聲音喔！',
    steps: [
      '選大於寶寶手掌、無小零件的搖鈴',
      '輕碰他的手心讓他握住',
      '輕輕搖一搖發出聲音',
      '換另一隻手再試',
    ],
    followUps: ['他握住多久？哪隻手比較有力？'],
    safetyNotes: '搖鈴需一體成型、無可拆小零件，避免放入口中時脫落。',
    endingLine: '握得好緊，收起來休息囉。',
    minAge: 1,
    maxAge: 5,
    required: [],
    optional: [],
    zpd: ['canGrasp'],
    focus: ['fine_motor'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 2,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'sensory',
    fallback: false,
  },
  {
    title: '模仿吐舌頭',
    description: '面對面緩慢吐舌、張嘴，引導新生兒早期模仿。',
    openingLine: '看我，學我做做看～',
    steps: [
      '抱寶寶在離臉約 25 公分處',
      '緩慢伸出舌頭，停留幾秒',
      '收回，等他的反應',
      '重複幾次，給他時間',
    ],
    followUps: ['他有試著動嘴或吐舌嗎？'],
    safetyNotes: '抱穩頭頸，保持輕鬆。',
    endingLine: '你好會看著我，真聰明。',
    minAge: 0,
    maxAge: 4,
    required: [],
    optional: [],
    zpd: ['imitatesActions'],
    focus: ['social_cognitive'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 2,
    maxDur: 5,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '包巾安撫',
    description: '用包巾營造被擁抱的安全感，搭配輕拍幫助安定。',
    openingLine: '把你包緊緊，像被抱著一樣安心。',
    steps: [
      '用薄包巾依正確方式包裹（髖部留空間）',
      '橫抱輕搖',
      '在耳邊發出「噓～」聲',
      '感覺放鬆就漸漸放慢',
    ],
    followUps: null,
    safetyNotes: '包巾不過緊、髖關節可活動；入睡務必仰睡、臉部不被覆蓋。會翻身後停止包巾。',
    endingLine: '安心睡，馬麻/把拔在這裡。',
    minAge: 0,
    maxAge: 4,
    required: [],
    optional: [],
    zpd: ['selfSoothing'],
    focus: ['emotional'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'bedroom',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'calm_down',
    fallback: false,
  },
  {
    title: '黑白卡探索',
    description: '展示高對比黑白圖卡，刺激新生兒視覺發展。',
    openingLine: '來看看黑白的圖案，好特別！',
    steps: [
      '把黑白高對比卡放在眼前約 25 公分',
      '停留讓他對焦 5–10 秒',
      '緩慢左右移動',
      '換一張不同圖案',
    ],
    followUps: ['哪張圖案最吸引他？'],
    safetyNotes: '卡片邊緣需圓滑，勿讓寶寶抓咬。',
    endingLine: '看得好專心，下次再看新的。',
    minAge: 0,
    maxAge: 4,
    required: [],
    optional: [],
    zpd: [],
    focus: ['social_cognitive'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 2,
    maxDur: 6,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '對話式咕咕',
    description: '模仿並回應寶寶的咕咕聲，建立來回式（serve-and-return）對話。',
    openingLine: '你說「咕～」，馬麻/把拔也說「咕～」！',
    steps: [
      '面對寶寶等他發出聲音',
      '溫柔地模仿同樣的音',
      '停下來，給他「回話」的空檔',
      '他再發聲就再回應',
    ],
    followUps: ['他會一來一往地發聲嗎？'],
    safetyNotes: null,
    endingLine: '我們聊得真開心。',
    minAge: 1,
    maxAge: 6,
    required: [],
    optional: [],
    zpd: ['meaningfulBabble'],
    focus: ['language', 'social_cognitive'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 2,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'talk',
    fallback: false,
  },
  {
    title: '不同質地觸摸',
    description: '讓寶寶觸摸柔軟的不同材質，豐富觸覺經驗。',
    openingLine: '摸摸看，這個軟軟的，那個滑滑的～',
    steps: [
      '準備幾種安全材質（紗布、絨布、矽膠）',
      '輕碰寶寶的手掌與手臂',
      '說出感覺：「軟軟的」「滑滑的」',
      '觀察他的反應',
    ],
    followUps: ['他喜歡哪一種觸感？'],
    safetyNotes: '材質需乾淨、無鬆脫纖維或小零件；避免覆蓋口鼻。',
    endingLine: '摸了好多東西，手手好厲害。',
    minAge: 1,
    maxAge: 6,
    required: [],
    optional: [],
    zpd: [],
    focus: ['fine_motor', 'social_cognitive'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 2,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'sensory',
    fallback: false,
  },
  {
    title: '鈴聲找一找',
    description: '在不同方向發出輕柔聲音，引導寶寶尋找聲源。',
    openingLine: '咦？聲音從哪裡來呢？',
    steps: [
      '在寶寶一側輕搖鈴或輕喚',
      '等他轉頭或轉眼找聲音',
      '換另一側再來一次',
      '找到了就微笑稱讚',
    ],
    followUps: ['他會往聲音的方向轉嗎？'],
    safetyNotes: '聲音輕柔，避免太大聲驚嚇。',
    endingLine: '耳朵真靈，都找到了！',
    minAge: 2,
    maxAge: 6,
    required: [],
    optional: [],
    zpd: ['respondsToName'],
    focus: ['language', 'social_cognitive'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 2,
    maxDur: 6,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '抱著慢慢跳舞',
    description: '抱著寶寶隨輕柔音樂緩慢搖擺，安撫情緒、感受節奏。',
    openingLine: '我們抱著一起搖搖擺擺～',
    steps: ['抱穩寶寶貼近胸口', '放輕柔音樂或哼歌', '隨節奏緩慢左右搖擺', '感覺他放鬆就繼續'],
    followUps: null,
    safetyNotes: '支撐好頭頸，動作平穩不旋轉甩動。',
    endingLine: '跳舞好放鬆，抱緊緊。',
    minAge: 0,
    maxAge: 6,
    required: [],
    optional: [],
    zpd: ['selfSoothing'],
    focus: ['emotional'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'music',
    fallback: false,
  },
  {
    title: '趴姿玩具引導',
    description: '在 tummy time 前方放玩具，鼓勵抬頭與伸手。',
    openingLine: '趴著看，前面有好玩的喔！',
    steps: [
      '清醒且有人看顧時讓寶寶趴著',
      '在正前方放一個鮮豔玩具',
      '用聲音鼓勵他抬頭看',
      '撐 1–2 分鐘，累了翻回來',
    ],
    followUps: ['他抬頭多高？撐多久？'],
    safetyNotes: '只在清醒且全程看顧下進行；餵奶後勿立即趴。吐奶或哭鬧就停止。',
    endingLine: '抬頭好有力，翻回來抱抱。',
    minAge: 1,
    maxAge: 6,
    required: [],
    optional: [],
    zpd: ['canRoll'],
    focus: ['gross_motor'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 2,
    maxDur: 6,
    bedtimeSafe: false,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '輕柔白噪音',
    description: '用穩定的白噪音或「噓」聲營造類子宮環境，幫助安定。',
    openingLine: '噓～聽這個穩穩的聲音，放鬆下來。',
    steps: [
      '抱著或在嬰兒床邊',
      '發出穩定的「噓～」或播放白噪音',
      '配合輕拍背部的節奏',
      '情緒平穩後漸漸減弱',
    ],
    followUps: null,
    safetyNotes: '音量勿過大、音源勿太靠近耳朵；入睡仍須仰睡。',
    endingLine: '安靜下來了，好好休息。',
    minAge: 0,
    maxAge: 5,
    required: [],
    optional: [],
    zpd: ['selfSoothing'],
    focus: ['emotional'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'bedroom',
    minDur: 3,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'calm_down',
    fallback: false,
  },

  // ===================== EARLY_INFANT 3–6m =====================
  {
    title: '伸手抓吊飾',
    description: '在寶寶上方掛安全吊飾，鼓勵伸手、揮打與抓取。',
    openingLine: '上面有吊吊樂，伸手碰碰看！',
    steps: [
      '寶寶仰躺，在胸口上方吊安全玩具',
      '鼓勵他伸手揮打',
      '把吊飾降到剛好碰得到',
      '讓他成功抓到並拉一下',
    ],
    followUps: ['他用單手還是雙手揮？'],
    safetyNotes: '吊飾固定牢固、繩長安全（避免纏繞），無小零件。',
    endingLine: '抓到了！手手越來越厲害。',
    minAge: 3,
    maxAge: 7,
    required: [],
    optional: ['canGrasp'],
    zpd: ['canGrasp'],
    focus: ['fine_motor', 'gross_motor'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '翻身找玩具',
    description: '在側邊放玩具誘導，協助寶寶練習主動翻身。',
    openingLine: '玩具在那邊，翻過去拿拿看！',
    steps: [
      '寶寶仰躺，在一側稍遠處放玩具',
      '引導他的視線與肩膀轉向',
      '需要時輕扶臀部協助翻身',
      '翻到後讓他玩玩具當獎勵',
    ],
    followUps: ['他能自己翻多少？哪一邊比較順？'],
    safetyNotes: '在地墊上進行、移開周圍硬物；不強拉手臂。',
    endingLine: '翻身成功，好棒！',
    minAge: 3,
    maxAge: 7,
    required: [],
    optional: [],
    zpd: ['canRoll'],
    focus: ['gross_motor'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: false,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '躲貓貓初體驗',
    description: '用手或布短暫遮臉再出現，萌芽物體恆存概念。',
    openingLine: '馬麻/把拔不見了……躲貓貓！',
    steps: [
      '面對寶寶，用手遮住自己的臉',
      '停 1 秒後拿開說「躲貓貓！」',
      '觀察他的驚喜與笑',
      '用一條薄布再玩一次',
    ],
    followUps: ['他會期待你出現嗎？有沒有笑？'],
    safetyNotes: '遮布只遮自己、不遮寶寶口鼻。',
    endingLine: '哈哈，找到馬麻/把拔了！',
    minAge: 3,
    maxAge: 8,
    required: [],
    optional: [],
    zpd: ['objectPermanence'],
    focus: ['social_cognitive', 'emotional'],
    stimulation: 'medium',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '學我發聲',
    description: '模仿寶寶的牙牙學語並加入新音節，擴充發聲練習。',
    openingLine: '你說「巴巴」，我也說「巴巴」！',
    steps: [
      '等寶寶發出「啊」「巴」等音',
      '面對面模仿同樣的音',
      '加入新音節如「媽媽」「答答」',
      '給他時間回應再繼續',
    ],
    followUps: ['他會嘗試新的音嗎？'],
    safetyNotes: null,
    endingLine: '你的聲音越來越多了！',
    minAge: 3,
    maxAge: 7,
    required: [],
    optional: [],
    zpd: ['meaningfulBabble'],
    focus: ['language'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 2,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'talk',
    fallback: false,
  },
  {
    title: '坐抱看世界',
    description: '扶坐在腿上面向環境，邊看邊命名身邊事物。',
    openingLine: '我們坐好，看看周圍有什麼～',
    steps: [
      '讓寶寶扶坐在你腿上、背靠著你',
      '指著身邊物品慢慢命名',
      '讓他注視、伸手探索',
      '描述顏色與名稱',
    ],
    followUps: ['他對什麼最有興趣？'],
    safetyNotes: '全程扶好軀幹與頭頸，避免後仰。',
    endingLine: '看了好多東西，真有趣。',
    minAge: 3,
    maxAge: 7,
    required: [],
    optional: [],
    zpd: ['respondsToName'],
    focus: ['language', 'social_cognitive'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'talk',
    fallback: false,
  },
  {
    title: '發現我的腳丫',
    description: '引導寶寶看見、抓自己的腳，認識身體部位。',
    openingLine: '咦～這是誰的腳腳呀？是你的！',
    steps: [
      '寶寶仰躺，輕碰他的腳引起注意',
      '把他的手帶到腳上',
      '幫腳套上鮮豔襪子增加興趣',
      '說「這是你的腳腳」',
    ],
    followUps: ['他會自己去抓腳嗎？'],
    safetyNotes: '動作輕緩，不硬拉肢體。',
    endingLine: '找到自己的腳腳了，好厲害。',
    minAge: 3,
    maxAge: 7,
    required: [],
    optional: [],
    zpd: [],
    focus: ['gross_motor', 'social_cognitive'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 2,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'sensory',
    fallback: false,
  },
  {
    title: '搖一搖有聲音',
    description: '示範搖動發聲玩具，建立「動作→結果」的因果概念。',
    openingLine: '搖一搖，會有聲音喔，你試試！',
    steps: [
      '給寶寶一個好握的發聲玩具',
      '示範搖動發出聲音',
      '把玩具交給他，鼓勵自己搖',
      '他發出聲音就給回應',
    ],
    followUps: ['他發現是自己讓它響的嗎？'],
    safetyNotes: '玩具一體成型、無小零件，可安全放入口探索。',
    endingLine: '是你讓它響的耶，好棒！',
    minAge: 3,
    maxAge: 7,
    required: [],
    optional: ['canGrasp'],
    zpd: ['canGrasp'],
    focus: ['fine_motor', 'social_cognitive'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'sensory',
    fallback: false,
  },
  {
    title: '軟布書翻翻',
    description: '一起看柔軟布書，指圖命名、培養早期閱讀興趣。',
    openingLine: '我們來看書書，這是什麼呀？',
    steps: ['抱著寶寶翻開布書', '指著圖案慢慢命名', '讓他摸一摸、抓一抓', '一頁停留久一點觀察反應'],
    followUps: ['他對哪一頁最有反應？'],
    safetyNotes: '布書乾淨、無鬆脫配件；讓他放口探索是正常的。',
    endingLine: '看書書好好玩，下次再看。',
    minAge: 3,
    maxAge: 8,
    required: [],
    optional: [],
    zpd: ['meaningfulBabble'],
    focus: ['language'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'read',
    fallback: false,
  },
  {
    title: '洗澡踢踢水',
    description: '洗澡時讓寶寶感受水的觸感、練習踢腿。',
    openingLine: '洗澡時間到，踢踢水好涼快～',
    steps: [
      '在安全水溫、淺水中托好寶寶',
      '輕撥水讓他感受',
      '鼓勵他踢腿濺起水花',
      '邊玩邊描述「踢踢、嘩啦」',
    ],
    followUps: ['他喜歡水花的感覺嗎？'],
    safetyNotes: '⚠️ 全程一手托穩、絕不可單獨留置；水位淺、水溫適中，浴室防滑。',
    endingLine: '洗得香香的，抱起來擦乾。',
    minAge: 3,
    maxAge: 8,
    required: [],
    optional: [],
    zpd: [],
    focus: ['gross_motor', 'emotional'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: false,
    companionType: 'sensory',
    fallback: false,
  },
  {
    title: '溫和飛高高',
    description: '平穩地把寶寶輕輕舉起又放下，體驗空間移動與互動的喜悅。',
    openingLine: '準備好了嗎？要飛高高囉～',
    steps: [
      '雙手穩穩托住寶寶軀幹與頭頸',
      '平穩地輕輕上抬再放下',
      '配合「飛～」的聲音與微笑',
      '看他的反應決定要不要再來',
    ],
    followUps: ['他露出期待或笑容了嗎？'],
    safetyNotes: '⚠️ 動作輕緩平穩，絕對不可用力搖晃或拋接（嬰兒搖晃症候群風險）。',
    endingLine: '飛得好開心，回到地面抱抱。',
    minAge: 4,
    maxAge: 8,
    required: [],
    optional: [],
    zpd: [],
    focus: ['gross_motor', 'emotional'],
    stimulation: 'high',
    playType: 'parallel',
    resources: [],
    space: 'living_room',
    minDur: 2,
    maxDur: 6,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: false,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '安全探索籃',
    description: '提供一籃安全的大型日常物件，讓寶寶自由抓握探索。',
    openingLine: '這一籃都可以摸摸看，挑一個吧！',
    steps: [
      '準備一籃大於拳頭、安全乾淨的物件（木湯匙、矽膠杯、布球）',
      '放在寶寶面前',
      '讓他自己抓取、翻看、放口探索',
      '描述他拿起的東西',
    ],
    followUps: ['他對哪個物件停留最久？'],
    safetyNotes: '所有物件須大於寶寶口腔、無小零件、無尖角，全程看顧。',
    endingLine: '探索得真認真，收進籃子裡。',
    minAge: 4,
    maxAge: 9,
    required: [],
    optional: ['canGrasp'],
    zpd: ['canPincerGrip'],
    focus: ['fine_motor', 'social_cognitive'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'sensory',
    fallback: false,
  },
  {
    title: '手指謠唱唱',
    description: '邊唱簡單手指謠邊輕碰寶寶手指，連結語言、節奏與觸覺。',
    openingLine: '我們來唱手指謠，一根手指頭～',
    steps: [
      '抱著寶寶，唱一首簡單兒歌',
      '配合歌詞輕點他的手指或手心',
      '在重複句停頓製造期待',
      '反覆同一首讓他熟悉',
    ],
    followUps: ['他對重複的段落有反應嗎？'],
    safetyNotes: null,
    endingLine: '唱得好開心，再來一首。',
    minAge: 3,
    maxAge: 9,
    required: [],
    optional: [],
    zpd: ['meaningfulBabble'],
    focus: ['language', 'social_cognitive'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'music',
    fallback: false,
  },
  {
    title: '鏡子表情模仿',
    description: '對著鏡子或面對面做誇張表情，引導寶寶觀察與模仿。',
    openingLine: '看我做鬼臉，你也試試看～',
    steps: [
      '面對寶寶或一起看安全鏡',
      '做誇張的笑、驚訝、嘟嘴',
      '每個表情停留讓他觀察',
      '等他嘗試模仿就熱情回應',
    ],
    followUps: ['他模仿了哪個表情？'],
    safetyNotes: '使用安全鏡，勿讓寶寶單獨拿取。',
    endingLine: '你的表情好可愛，學得真像！',
    minAge: 4,
    maxAge: 9,
    required: [],
    optional: [],
    zpd: ['imitatesActions'],
    focus: ['social_cognitive', 'emotional'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 2,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '趴姿伸手拿',
    description: '在 tummy time 時把玩具放稍遠，鼓勵伸手與重心轉移。',
    openingLine: '趴著伸手拿，加油搆得到！',
    steps: [
      '清醒看顧下讓寶寶趴著',
      '把玩具放在伸手可及的前方',
      '鼓勵他抬胸、伸手去拿',
      '搆到就讓他玩一下',
    ],
    followUps: ['他能單手離地伸手嗎？'],
    safetyNotes: '清醒且全程看顧；餵奶後勿立即趴；疲累或哭鬧就停止。',
    endingLine: '伸手拿到了，力氣好大！',
    minAge: 4,
    maxAge: 9,
    required: [],
    optional: ['canGrasp'],
    zpd: ['canRoll', 'canGrasp'],
    focus: ['gross_motor', 'fine_motor'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: false,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '安靜抱抱深呼吸',
    description: '把寶寶抱在胸前，用你平穩的呼吸與心跳幫助他共調情緒。',
    openingLine: '我們抱緊緊，一起慢慢呼吸～',
    steps: [
      '把寶寶直立抱在胸口、貼近你',
      '自己放慢、加深呼吸',
      '輕拍背部配合節奏',
      '感覺他跟著放鬆下來',
    ],
    followUps: null,
    safetyNotes: '支撐好頭頸；若他持續哭鬧不安，檢查是否餓了/尿布/不適。',
    endingLine: '慢慢放鬆，馬麻/把拔都在。',
    minAge: 0,
    maxAge: 9,
    required: [],
    optional: [],
    zpd: ['selfSoothing'],
    focus: ['emotional'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'calm_down',
    fallback: false,
  },
]
