// 內容批次：12–24 個月（EARLY_WALKER 12–18m + TODDLER_TALKER 18–24m）共 30 條。
// 里程碑：獨立走→跑、塗鴉、疊積木、10+ 詞→兩字句、假扮萌芽、輪流、爬樓梯、情緒命名。
// 全部可安全在家、需成人看顧；移動/工具類標安全註記並排除睡前/生病日。非醫療內容。

export const activities = [
  // ===================== EARLY_WALKER 12–18m =====================
  {
    title: '走走拿玩具',
    description: '在不遠處放玩具，鼓勵剛會走的寶寶走過去拿，練習平衡。',
    openingLine: '玩具在那邊，自己走過去拿拿看～',
    steps: ['讓寶寶站穩', '在幾步外放他喜歡的玩具', '張開手鼓勵他走過來', '到了給大大的擁抱'],
    followUps: ['他能連走幾步？'],
    safetyNotes: '地面平整淨空、移開硬角家具、在旁保護。',
    endingLine: '走得越來越穩了，好棒！',
    minAge: 12,
    maxAge: 18,
    required: ['canWalkIndependently'],
    optional: [],
    zpd: [],
    focus: ['gross_motor'],
    stimulation: 'medium',
    playType: 'parallel',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '蠟筆塗鴉初體驗',
    description: '用粗蠟筆在大紙上自由塗畫，練習握筆與手眼協調。',
    openingLine: '我們來畫畫，紅紅綠綠塗滿滿！',
    steps: ['鋪大張紙、給好握的粗蠟筆', '示範隨意畫線、畫圈', '讓他自由塗鴉', '描述他畫的顏色'],
    followUps: ['他最愛哪個顏色？'],
    safetyNotes: '用無毒可水洗蠟筆，全程看顧避免入口。',
    endingLine: '畫得真精彩，貼起來欣賞！',
    minAge: 13,
    maxAge: 20,
    required: [],
    optional: [],
    zpd: ['canScribble'],
    focus: ['fine_motor'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'creative',
    fallback: false,
  },
  {
    title: '疊積木比高',
    description: '練習把積木一塊塊往上疊，挑戰能疊幾塊。',
    openingLine: '我們來疊高高，可以疊幾塊呢？',
    steps: ['給幾塊好疊的大積木', '示範疊兩三塊', '讓他自己疊', '一起數數疊了幾塊'],
    followUps: ['他能疊幾塊不倒？'],
    safetyNotes: '積木無小零件、邊角圓鈍。',
    endingLine: '疊得好高，厲害的小工程師！',
    minAge: 12,
    maxAge: 20,
    required: [],
    optional: [],
    zpd: ['canStackBlocks3'],
    focus: ['fine_motor'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '這是什麼呀',
    description: '指著日常物品問「這是什麼」，鼓勵寶寶說出名稱、擴充詞彙。',
    openingLine: '這是什麼呀？你來告訴我～',
    steps: ['指著熟悉物品問名稱', '等他回答或示範說一次', '他說出就熱情肯定', '換下一樣東西'],
    followUps: ['他會說哪些新詞了？'],
    safetyNotes: null,
    endingLine: '你會說好多詞了，真棒！',
    minAge: 12,
    maxAge: 22,
    required: [],
    optional: [],
    zpd: ['hasVocabulary10'],
    focus: ['language'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'talk',
    fallback: false,
  },
  {
    title: '踢踢小球',
    description: '把球放腳邊鼓勵寶寶踢，練習單腳平衡與下肢力量。',
    openingLine: '用腳踢踢看，球球滾出去囉！',
    steps: ['把軟球放在寶寶腳前', '示範輕踢一下', '扶著他練習踢', '球滾出去一起歡呼'],
    followUps: ['他踢到球了嗎？'],
    safetyNotes: '球柔軟、場地淨空、在旁穩住避免跌倒。',
    endingLine: '踢得真好，小小足球員！',
    minAge: 14,
    maxAge: 22,
    required: ['canWalkIndependently'],
    optional: [],
    zpd: [],
    focus: ['gross_motor'],
    stimulation: 'medium',
    playType: 'parallel',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '形狀放進洞',
    description: '玩形狀配對盒，把形狀塊放進對應的洞，練習配對與手腕轉動。',
    openingLine: '圓圓的放這個洞，找找看～',
    steps: ['拿形狀配對盒與大形狀塊', '示範把圓形放進圓洞', '讓他嘗試配對', '放對了一起拍手'],
    followUps: ['他最先學會哪個形狀？'],
    safetyNotes: '形狀塊需大於口腔、無小零件。',
    endingLine: '配對成功，好聰明！',
    minAge: 14,
    maxAge: 24,
    required: [],
    optional: [],
    zpd: ['canPincerGrip'],
    focus: ['fine_motor', 'social_cognitive'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '學動物走路',
    description: '模仿小狗爬、兔子跳、大象走，結合大動作與模仿想像。',
    openingLine: '我們來學小動物走路，汪汪～',
    steps: ['示範學小狗在地上爬', '換兔子雙腳跳', '再學大象慢慢走', '讓他跟著模仿'],
    followUps: ['他最愛學哪種動物？'],
    safetyNotes: '在軟墊或淨空區進行、在旁保護。',
    endingLine: '動物模仿秀好精彩！',
    minAge: 15,
    maxAge: 24,
    required: ['canWalkIndependently'],
    optional: [],
    zpd: [],
    focus: ['gross_motor', 'social_cognitive'],
    stimulation: 'high',
    playType: 'parallel',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: false,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '丟球進籃',
    description: '把球丟進大盆或籃子，練習瞄準、放手與手眼協調。',
    openingLine: '瞄準籃子，球球投進去！',
    steps: ['放一個大盆或籃子在近處', '給寶寶幾顆軟球', '示範丟進去', '投進了一起歡呼'],
    followUps: ['他投進幾顆？'],
    safetyNotes: '球柔軟、籃子穩固不傾倒。',
    endingLine: '投籃高手，太厲害了！',
    minAge: 14,
    maxAge: 24,
    required: [],
    optional: [],
    zpd: [],
    focus: ['gross_motor', 'fine_motor'],
    stimulation: 'medium',
    playType: 'parallel',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '大塊拼圖',
    description: '玩 2–4 片的大塊拼圖，練習觀察、配對與問題解決。',
    openingLine: '這片放哪裡呢？我們一起拼！',
    steps: ['選 2–4 片的大塊拼圖', '示範拼一片', '引導他觀察形狀與圖案', '完成一起喝采'],
    followUps: ['他能自己拼幾片？'],
    safetyNotes: '拼片夠大、無小零件。',
    endingLine: '拼好了，好厲害的小偵探！',
    minAge: 16,
    maxAge: 26,
    required: [],
    optional: [],
    zpd: [],
    focus: ['fine_motor', 'social_cognitive'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '情緒繪本共讀',
    description: '讀有情緒表情的繪本，指著臉問「他是開心還是難過」。',
    openingLine: '看看書裡的小朋友，他現在什麼心情？',
    steps: ['選有臉部表情的繪本', '指著角色問情緒', '示範說「他很開心」', '連結到他自己的感受'],
    followUps: ['他能說出幾種心情？'],
    safetyNotes: null,
    endingLine: '你越來越懂心情了，真棒。',
    minAge: 15,
    maxAge: 26,
    required: [],
    optional: [],
    zpd: [],
    focus: ['emotional', 'language'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'read',
    fallback: false,
  },
  {
    title: '推拉玩具散步',
    description: '推或拉有輪子的玩具走，練習穩定行走與控制方向。',
    openingLine: '推著小車車，我們去散步囉～',
    steps: ['給一個推拉玩具', '示範推著往前走', '讓他控制方向繞一圈', '描述「走、停、轉彎」'],
    followUps: ['他能控制方向嗎？'],
    safetyNotes: '路徑淨空、地面平整、在旁保護。',
    endingLine: '推著走真穩，好棒！',
    minAge: 13,
    maxAge: 22,
    required: ['canWalkIndependently'],
    optional: [],
    zpd: [],
    focus: ['gross_motor'],
    stimulation: 'medium',
    playType: 'solitary',
    resources: [],
    space: 'living_room',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '動作兒歌',
    description: '唱「頭兒肩膀膝腳趾」等動作兒歌，連結語言、身體部位與模仿。',
    openingLine: '頭兒、肩膀、膝、腳趾，一起唱！',
    steps: ['唱動作兒歌示範指部位', '握他的手一起指', '放慢讓他跟上', '反覆加深記憶'],
    followUps: ['他會指對哪些部位？'],
    safetyNotes: null,
    endingLine: '唱跳得真好，再來一次！',
    minAge: 14,
    maxAge: 26,
    required: [],
    optional: [],
    zpd: ['imitatesActions'],
    focus: ['language', 'gross_motor'],
    stimulation: 'medium',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: false,
    sickDaySafe: true,
    elderly: true,
    companionType: 'music',
    fallback: false,
  },

  // ===================== TODDLER_TALKER 18–24m =====================
  {
    title: '兩個字說說看',
    description: '把單詞擴成兩字短句示範，鼓勵孩子說出「要喝」「車車來」。',
    openingLine: '你說「車」，我們再加一個字：「車車來」！',
    steps: ['聽孩子說出單詞', '示範擴成兩字句', '鼓勵他跟著說', '在生活中自然重複'],
    followUps: ['他開始說兩個字了嗎？'],
    safetyNotes: null,
    endingLine: '會說短句了，好厲害！',
    minAge: 18,
    maxAge: 28,
    required: [],
    optional: [],
    zpd: ['usesTwoWordPhrases'],
    focus: ['language'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 10,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'talk',
    fallback: false,
  },
  {
    title: '假扮煮飯飯',
    description: '用玩具鍋碗假裝煮飯、餵娃娃，發展假扮遊戲與語言。',
    openingLine: '我們來煮飯飯，今天煮什麼好呢？',
    steps: ['擺出玩具廚具', '假裝切菜、攪拌、煮', '邀孩子餵娃娃或你吃', '描述動作與味道'],
    followUps: ['他想出什麼假扮情節？'],
    safetyNotes: '玩具無小零件、無尖角。',
    endingLine: '煮得真好吃，謝謝小廚師！',
    minAge: 18,
    maxAge: 30,
    required: [],
    optional: [],
    zpd: ['symbolicPlay'],
    focus: ['social_cognitive', 'language'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 5,
    maxDur: 15,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'creative',
    fallback: false,
  },
  {
    title: '輪流堆積木',
    description: '一人放一塊輪流堆塔，練習等待與輪流的社交規則。',
    openingLine: '換我放一塊，再換你，一人一次喔～',
    steps: ['說明「輪流放」的規則', '你放一塊再請他放', '等待時數「一、二」', '塔倒了一起笑著重來'],
    followUps: ['他能等待輪到自己嗎？'],
    safetyNotes: '積木無小零件。',
    endingLine: '會輪流了，真有耐心！',
    minAge: 18,
    maxAge: 30,
    required: [],
    optional: [],
    zpd: ['canTakeTurns'],
    focus: ['social_cognitive'],
    stimulation: 'low',
    playType: 'cooperative',
    resources: [],
    space: 'anywhere',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '扶著爬樓梯',
    description: '扶著扶手或大人手，練習一階一階上下樓梯。',
    openingLine: '抓好扶手，我們一階一階上樓～',
    steps: ['牽手或讓他扶穩扶手', '一階一階慢慢上', '數「一階、二階」', '下樓更小心、面向階梯'],
    followUps: ['他上下幾階了？'],
    safetyNotes: '⚠️ 全程牽手或緊貼保護、絕不放手；裝設樓梯防護欄。',
    endingLine: '爬樓梯好棒，腳力越來越好！',
    minAge: 18,
    maxAge: 28,
    required: ['canWalkIndependently'],
    optional: [],
    zpd: ['canClimbStairs'],
    focus: ['gross_motor'],
    stimulation: 'medium',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: false,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '分顏色排排站',
    description: '把同色的物品分在一起，練習顏色辨識與分類。',
    openingLine: '紅色的放這邊，藍色的放那邊～',
    steps: ['準備兩三種顏色的安全物件', '示範依顏色分類', '讓他把同色放一起', '說出顏色名稱'],
    followUps: ['他分對了幾種顏色？'],
    safetyNotes: '物件大於口腔、無小零件。',
    endingLine: '分得真整齊，好聰明！',
    minAge: 18,
    maxAge: 30,
    required: [],
    optional: [],
    zpd: [],
    focus: ['social_cognitive', 'fine_motor'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '追泡泡跑',
    description: '吹泡泡讓孩子追、拍，練習跑動、瞄準與大笑放電。',
    openingLine: '泡泡飛起來囉，快去追、去拍！',
    steps: ['在安全空地吹泡泡', '鼓勵孩子追著拍破', '比比看誰拍到多', '玩到開心為止'],
    followUps: ['他拍破幾個泡泡？'],
    safetyNotes: '地面防滑乾燥、場地淨空；泡泡水勿入口眼。',
    endingLine: '追泡泡好開心，跑得真快！',
    minAge: 18,
    maxAge: 36,
    required: ['canWalkIndependently'],
    optional: [],
    zpd: [],
    focus: ['gross_motor'],
    stimulation: 'high',
    playType: 'parallel',
    resources: [],
    space: 'outdoor',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: false,
    sickDaySafe: false,
    elderly: false,
    companionType: 'outdoor',
    fallback: false,
  },
  {
    title: '貼紙貼貼樂',
    description: '撕貼紙貼到紙上指定位置，練習拇指食指與專注。',
    openingLine: '撕下貼紙，貼到這裡來～',
    steps: ['給大張貼紙與底紙', '示範撕下貼好', '讓他撕貼、自由創作', '欣賞他的貼紙畫'],
    followUps: ['他能自己撕下貼紙嗎？'],
    safetyNotes: '貼紙夠大、全程看顧避免入口。',
    endingLine: '貼紙畫好美，貼起來展示！',
    minAge: 18,
    maxAge: 30,
    required: [],
    optional: [],
    zpd: ['canPincerGrip'],
    focus: ['fine_motor'],
    stimulation: 'low',
    playType: 'solitary',
    resources: [],
    space: 'anywhere',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'creative',
    fallback: false,
  },
  {
    title: '假裝打電話',
    description: '用玩具電話假裝通話，發展假扮、語言與社交對話。',
    openingLine: '鈴鈴～電話響了，喂？你好！',
    steps: ['拿玩具或手作電話', '假裝撥號、說「喂」', '一問一答來回對話', '請他打給娃娃或家人'],
    followUps: ['他會說哪些對話？'],
    safetyNotes: null,
    endingLine: '講電話好有禮貌，再見囉！',
    minAge: 18,
    maxAge: 30,
    required: [],
    optional: [],
    zpd: ['usesTwoWordPhrases', 'symbolicPlay'],
    focus: ['language', 'social_cognitive'],
    stimulation: 'low',
    playType: 'cooperative',
    resources: [],
    space: 'anywhere',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'talk',
    fallback: false,
  },
  {
    title: '收玩具歌',
    description: '邊唱收拾歌邊把玩具歸位，建立routine與責任感。',
    openingLine: '玩具玩具回家囉，我們一起收～',
    steps: ['玩完唱固定的「收玩具歌」', '示範把玩具放回籃子', '邀孩子一起收', '收完給大大的讚'],
    followUps: ['他願意一起收嗎？'],
    safetyNotes: null,
    endingLine: '收得真乾淨，好棒的幫手！',
    minAge: 18,
    maxAge: 36,
    required: [],
    optional: [],
    zpd: [],
    focus: ['social_cognitive', 'emotional'],
    stimulation: 'low',
    playType: 'cooperative',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '等一下也沒關係',
    description: '用短暫等待的小遊戲，練習承受「等一下」的小挫折。',
    openingLine: '數到三才能拿喔，一、二、三，給你！',
    steps: ['拿他想要的安全物件', '說「等一下，數到三」', '一起數到三再給', '逐漸拉長一點等待'],
    followUps: ['他能等多久不哭鬧？'],
    safetyNotes: '等待時間短、保持輕鬆，避免造成挫折過度。',
    endingLine: '會等一下了，好有耐心！',
    minAge: 20,
    maxAge: 34,
    required: [],
    optional: [],
    zpd: ['toleratesFrustration'],
    focus: ['emotional', 'social_cognitive'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 2,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'play',
    fallback: false,
  },
  {
    title: '心情臉譜',
    description: '做開心、難過、生氣的表情讓孩子認，命名情緒。',
    openingLine: '看我的臉，這是開心還是生氣呢？',
    steps: ['做誇張的情緒表情', '問孩子「這是什麼心情」', '示範說出情緒詞', '請他也做做看'],
    followUps: ['他能認出幾種情緒？'],
    safetyNotes: null,
    endingLine: '你好會看心情，真棒！',
    minAge: 18,
    maxAge: 36,
    required: [],
    optional: [],
    zpd: [],
    focus: ['emotional', 'social_cognitive'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'anywhere',
    minDur: 3,
    maxDur: 8,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'talk',
    fallback: false,
  },
  {
    title: '睡前說今天',
    description: '睡前用簡單句子回顧今天做了什麼，連結語言、記憶與安定。',
    openingLine: '躺好，我們說說今天玩了什麼～',
    steps: ['調暗燈光、躺下', '用簡單句說今天的事', '停頓讓他補一兩個字', '以溫柔的晚安收尾'],
    followUps: ['他記得今天哪件事？'],
    safetyNotes: null,
    endingLine: '今天很棒，晚安囉。',
    minAge: 20,
    maxAge: 40,
    required: [],
    optional: [],
    zpd: ['usesTwoWordPhrases'],
    focus: ['language', 'emotional'],
    stimulation: 'low',
    playType: 'parallel',
    resources: [],
    space: 'bedroom',
    minDur: 4,
    maxDur: 12,
    bedtimeSafe: true,
    sickDaySafe: true,
    elderly: true,
    companionType: 'calm_down',
    fallback: false,
  },
]
