-- ============================================================================
-- Seed（自動產生，請勿手改；改 scripts/content/activities-36-60m.mjs 後重跑 build-seed.mjs）
-- 批次：20260624050000_seed_activity_library_36_60m
-- 共 24 筆。所有欄位值已通過 schema 允許集合驗證。
-- ============================================================================

INSERT INTO public.companion_activities (
  title, description, opening_line, steps, follow_up_questions, safety_notes, ending_line,
  min_age_months, max_age_months,
  required_capabilities, optional_capabilities, zpd_targets, developmental_focus,
  stimulation_level, play_type, required_resources, space_requirement,
  min_duration_minutes, max_duration_minutes,
  is_bedtime_safe, is_sick_day_safe, elderly_friendly,
  companion_type, is_fallback, is_active
) VALUES
('單腳站站看', '練習單腳站立與單腳跳，發展平衡與下肢控制。', '像金雞一樣，單腳站站看，幾秒不倒？', '["示範單腳站、數秒","牽手陪他試一次","放手讓他自己站","再挑戰單腳小跳"]', '["他單腳能站幾秒？"]', '地面防滑、周圍淨空、在旁保護。', '平衡感真棒，金雞獨立成功！',
 36, 54,
 '{"canRun"}', '{}', '{"canHopOneFoot"}', '{"gross_motor"}',
 'medium', 'solitary', '{}', 'living_room',
 3, 10,
 FALSE, TRUE, TRUE,
 'play', FALSE, TRUE),

('安全剪刀剪一剪', '用兒童安全剪刀剪紙，練習雙手協調與工具使用。', '我們用小剪刀，沿著線剪剪看～', '["給兒童安全剪刀與畫線的紙","示範正確握法與開合","陪他沿粗線剪","剪下的紙拼成圖案"]', '["他能沿線剪了嗎？"]', '⚠️ 只用圓頭兒童安全剪刀、全程在旁監督、用畢立即收好。', '剪得真好，小手好靈巧！',
 36, 54,
 '{}', '{}', '{"canUseScissors"}', '{"fine_motor"}',
 'low', 'solitary', '{}', 'kitchen',
 5, 15,
 TRUE, TRUE, TRUE,
 'creative', FALSE, TRUE),

('畫一個人', '引導孩子畫出有頭、身體、手腳的人，發展表徵繪畫。', '我們來畫一個人，先畫圓圓的頭～', '["示範畫頭、身體、手腳","請他加上眼睛嘴巴","讓他畫自己的版本","一起說畫了誰"]', '["他畫的人有幾個部位？"]', '用無毒可水洗筆。', '畫得好棒，是誰呀？',
 36, 54,
 '{}', '{}', '{"canDrawCircle"}', '{"fine_motor","social_cognitive"}',
 'low', 'solitary', '{}', 'anywhere',
 5, 15,
 TRUE, TRUE, TRUE,
 'creative', FALSE, TRUE),

('說一件好玩的事', '請孩子描述今天做了什麼，練習敘事與時間順序。', '今天有什麼好玩的事？說給我聽～', '["問一個開放問題","用「然後呢」引導他繼續","幫他補上時間順序詞","專心聽並回應"]', '["他能說出事情的先後嗎？"]', NULL, '說得好清楚，真會講！',
 36, 54,
 '{}', '{}', '{"canDescribeEvents"}', '{"language"}',
 'low', 'parallel', '{}', 'anywhere',
 4, 12,
 TRUE, TRUE, TRUE,
 'talk', FALSE, TRUE),

('合作蓋城堡', '一起用積木合力蓋一座城堡，練習合作、分工與協商。', '我們一起蓋一座大城堡，你負責這邊！', '["一起決定要蓋什麼","分工各自負責一部分","討論怎麼接起來","完成一起欣賞"]', '["你們怎麼分工的？"]', '積木無小零件、注意倒塌方向。', '合作蓋得好棒，團隊真厲害！',
 36, 56,
 '{}', '{}', '{"cooperativePlay"}', '{"social_cognitive"}',
 'low', 'cooperative', '{}', 'living_room',
 6, 18,
 TRUE, TRUE, TRUE,
 'play', FALSE, TRUE),

('角色扮演遊戲', '扮演老師、消防員、爸媽等角色演短劇，發展想像與社會理解。', '今天你想當誰呢？我們來演一場！', '["一起選角色與情境","用道具或服裝裝扮","即興演出小情節","互換角色再演"]', '["他最愛扮演什麼角色？"]', '道具安全、無小零件與尖角。', '演得好精彩，小演員！',
 36, 60,
 '{}', '{}', '{"cooperativePlay"}', '{"social_cognitive","language"}',
 'medium', 'cooperative', '{}', 'anywhere',
 6, 18,
 TRUE, TRUE, TRUE,
 'creative', FALSE, TRUE),

('跳圈圈', '在地上排圈圈讓孩子雙腳或單腳跳進跳出，練習跳躍與協調。', '一個圈一個圈，跳進去，跳！', '["用呼拉圈或膠帶排幾個圈","示範雙腳跳進每個圈","挑戰單腳跳","加快或變化路線"]', '["他能連跳幾個圈？"]', '地面防滑、圈固定不滑、在旁保護。', '跳得又快又穩，好厲害！',
 38, 58,
 '{"canJumpBothFeet"}', '{}', '{"canHopOneFoot"}', '{"gross_motor"}',
 'high', 'solitary', '{}', 'outdoor',
 4, 12,
 FALSE, FALSE, FALSE,
 'outdoor', FALSE, TRUE),

('數量配對 1 到 5', '把數字與對應數量的物品配對，建立數與量的連結。', '數字 3 要配幾個積木呢？來數數～', '["排出數字卡 1–5","請他放對應數量的物品","一起點數確認","逐步增加難度"]', '["他能配對到幾？"]', '物件無小零件。', '數量配對全對，數學小高手！',
 38, 58,
 '{}', '{}', '{}', '{"social_cognitive","language"}',
 'low', 'cooperative', '{}', 'anywhere',
 5, 15,
 TRUE, TRUE, TRUE,
 'play', FALSE, TRUE),

('走平衡木', '在地上的板子或膠帶線上練習穩定行走與轉身。', '張開手，走過獨木橋，別掉下河喔～', '["用矮板或膠帶當平衡木","示範張手慢走","陪他走一次","挑戰倒退或轉身"]', '["他能走到底不掉嗎？"]', '板子貼地穩固、周圍鋪軟墊、在旁保護。', '平衡感真好，過橋成功！',
 36, 56,
 '{"canWalkIndependently"}', '{}', '{}', '{"gross_motor"}',
 'medium', 'solitary', '{}', 'living_room',
 4, 12,
 FALSE, TRUE, TRUE,
 'play', FALSE, TRUE),

('撕貼拼貼畫', '撕色紙拼貼成圖案，練習手部控制、構圖與創意。', '撕一撕、貼一貼，拼出一幅畫！', '["準備色紙與膠水","示範撕成小片貼出形狀","讓他自由拼貼","一起命名作品"]', '["他拼出什麼圖？"]', '膠水無毒、全程看顧；用畢洗手。', '拼貼好有創意，貼牆上展示！',
 36, 56,
 '{}', '{}', '{}', '{"fine_motor","social_cognitive"}',
 'low', 'solitary', '{}', 'kitchen',
 6, 18,
 TRUE, TRUE, TRUE,
 'creative', FALSE, TRUE),

('情緒怎麼解決', '用情境討論「如果生氣／難過可以怎麼辦」，建立情緒因應策略。', '如果玩具被搶走，我們可以怎麼辦呢？', '["提出一個常見情緒情境","問他「可以怎麼做」","一起想出幾種方法","練習說出來或演一遍"]', '["他想到哪些好方法？"]', NULL, '你想到好多辦法，真棒！',
 36, 60,
 '{}', '{}', '{"toleratesFrustration"}', '{"emotional","social_cognitive"}',
 'low', 'parallel', '{}', 'anywhere',
 4, 12,
 TRUE, TRUE, TRUE,
 'talk', FALSE, TRUE),

('顏色混合魔法', '用顏料混色觀察變化，認識顏色並培養好奇與觀察。', '紅色加黃色，會變成什麼顏色呢？', '["準備紅黃藍可水洗顏料","示範兩色相混","請他猜會變什麼色","一起記錄新顏色"]', '["他發現哪些新顏色？"]', '顏料無毒可水洗、全程看顧避免入口；鋪好桌面。', '變出新顏色了，好神奇！',
 38, 58,
 '{}', '{}', '{}', '{"fine_motor","social_cognitive"}',
 'low', 'cooperative', '{}', 'kitchen',
 6, 18,
 TRUE, TRUE, TRUE,
 'creative', FALSE, TRUE),

('練習寫筆畫', '描寫直線、橫線、圓等基本筆畫，為寫字打基礎。', '跟著虛線描描看，一筆一畫慢慢來～', '["準備有虛線筆畫的紙","示範正確握筆描寫","陪他描幾筆","進階描自己名字的第一個字"]', '["他握筆穩了嗎？"]', '用無毒筆、注意握筆姿勢不過度用力。', '寫得真認真，越來越棒！',
 48, 60,
 '{}', '{}', '{"canWriteName"}', '{"fine_motor"}',
 'low', 'solitary', '{}', 'anywhere',
 5, 15,
 TRUE, TRUE, TRUE,
 'creative', FALSE, TRUE),

('你問我答', '輪流問答（喜歡什麼、為什麼），練習來回對話與表達理由。', '我問你答，再換你問我，準備好了嗎？', '["輪流問對方問題","鼓勵他回答並說原因","追問「為什麼呢」","互換主導"]', '["他能說出理由嗎？"]', NULL, '聊得真好，你好會表達！',
 48, 60,
 '{}', '{}', '{"canHaveConversation"}', '{"language","social_cognitive"}',
 'low', 'cooperative', '{}', 'anywhere',
 5, 15,
 TRUE, TRUE, TRUE,
 'talk', FALSE, TRUE),

('一起玩桌遊', '玩簡單的擲骰／配對桌遊，練習遵守規則、輪流與輸贏情緒。', '我們來玩桌遊，輪流擲骰子，要守規則喔～', '["選一個簡單規則的桌遊","一起讀規則","輪流進行","討論輸贏時的心情"]', '["他能接受輸的結果嗎？"]', '配件無小零件（或全程監督）。', '玩得好開心，規則都守住了！',
 48, 60,
 '{}', '{}', '{"canFollowRules","cooperativePlay"}', '{"social_cognitive","emotional"}',
 'low', 'cooperative', '{}', 'anywhere',
 6, 20,
 TRUE, TRUE, TRUE,
 'play', FALSE, TRUE),

('闖關小任務', '設計幾個步驟的小任務一起完成，練習合作、計畫與堅持。', '今天有三個小任務，我們一起闖關吧！', '["一起設定 2–3 個關卡任務","分工或合作完成","每完成一關擊掌","全部完成給獎勵"]', '["哪一關最有挑戰？"]', '任務內容安全、避免危險動作。', '全部闖關成功，超強團隊！',
 48, 60,
 '{}', '{}', '{"cooperativePlay"}', '{"social_cognitive","emotional"}',
 'medium', 'cooperative', '{}', 'anywhere',
 8, 20,
 FALSE, TRUE, TRUE,
 'play', FALSE, TRUE),

('拍球接球', '練習拍球、丟接球，發展手眼協調與反應。', '球丟給你，接住！再丟回來～', '["用適中大小的球","近距離互相丟接","練習拍球落地反彈","拉開距離增加挑戰"]', '["他能連續接幾次？"]', '球軟硬適中、場地淨空、避免衝撞。', '接得真準，球技進步了！',
 48, 60,
 '{"canRun"}', '{}', '{"canHopOneFoot"}', '{"gross_motor"}',
 'high', 'cooperative', '{}', 'outdoor',
 5, 15,
 FALSE, FALSE, FALSE,
 'outdoor', FALSE, TRUE),

('數到十與加一', '數到 10、玩「再加一個是幾」，建立基礎數感與加法概念。', '三個再加一個，變成幾個呢？', '["用實物數到 10","玩「再加一個」","玩「拿走一個」","逐步用口頭計算"]', '["他能算加一減一嗎？"]', '物件無小零件。', '算得好快，數學小達人！',
 48, 60,
 '{}', '{}', '{}', '{"social_cognitive","language"}',
 'low', 'cooperative', '{}', 'anywhere',
 5, 15,
 TRUE, TRUE, TRUE,
 'talk', FALSE, TRUE),

('自己編故事', '用圖卡或玩偶當提示，請孩子編一個小故事，發展敘事與想像。', '從前從前……接下來發生什麼事呢？', '["給幾張圖卡或玩偶當角色","起個頭請他接故事","用問題引導情節發展","一起說出結局"]', '["他編出什麼情節？"]', '道具安全無小零件。', '故事好精彩，你是說故事高手！',
 48, 60,
 '{}', '{}', '{"canHaveConversation"}', '{"language"}',
 'low', 'cooperative', '{}', 'anywhere',
 6, 18,
 TRUE, TRUE, TRUE,
 'talk', FALSE, TRUE),

('摺紙小手作', '一起摺簡單的紙飛機、紙船，練習對邊對齊與步驟跟隨。', '我們來摺紙飛機，照步驟一起摺～', '["準備正方或長方紙","示範一步步摺、壓平","陪他對齊邊角","完成後試飛或玩"]', '["他能跟著步驟摺嗎？"]', '紙張邊緣注意割傷；作品玩耍時注意安全。', '摺得好棒，飛機飛得真遠！',
 48, 60,
 '{}', '{}', '{"canUseScissors"}', '{"fine_motor","social_cognitive"}',
 'low', 'cooperative', '{}', 'anywhere',
 6, 18,
 TRUE, TRUE, TRUE,
 'creative', FALSE, TRUE),

('分類整理玩具', '把玩具依類別／顏色分類收納，練習邏輯分類與物歸原位。', '我們來當整理達人，把玩具分類收好～', '["決定分類方式（類別或顏色）","一起把玩具分堆","放進對應的箱子","完成欣賞整齊的成果"]', '["他想到什麼分類方法？"]', NULL, '整理得好整齊，真厲害！',
 42, 60,
 '{}', '{}', '{}', '{"social_cognitive","emotional"}',
 'low', 'cooperative', '{}', 'anywhere',
 5, 15,
 TRUE, TRUE, TRUE,
 'play', FALSE, TRUE),

('小小幫廚', '一起做免火簡單點心（洗水果、拌沙拉），練習手部技巧與合作。', '今天當小幫廚，我們一起做點心！', '["挑免火安全的步驟（洗、拌、擺盤）","示範並陪他做","一起完成擺盤","開心享用成果"]', '["他最喜歡哪個步驟？"]', '⚠️ 避開刀具、熱源與生食風險；全程監督、做前後洗手。', '小幫廚太棒了，好好吃！',
 42, 60,
 '{}', '{}', '{"cooperativePlay"}', '{"fine_motor","social_cognitive"}',
 'low', 'cooperative', '{}', 'kitchen',
 8, 20,
 TRUE, TRUE, TRUE,
 'creative', FALSE, TRUE),

('認字找一找', '在書或招牌上找認得的字／注音，培養文字覺察與閱讀興趣。', '看看這頁，有沒有你認得的字？', '["翻開繪本或看生活中的字","指出一個常見字示範","請他找出相同的字","唸出來一起認"]', '["他認得哪些字了？"]', NULL, '認得好多字，快變小讀者了！',
 48, 60,
 '{}', '{}', '{"canHaveConversation"}', '{"language"}',
 'low', 'cooperative', '{}', 'anywhere',
 5, 15,
 TRUE, TRUE, TRUE,
 'read', FALSE, TRUE),

('睡前聊聊明天', '睡前一起說說明天想做的事，練習計畫表達與安定情緒。', '躺好，我們聊聊明天想做什麼呢？', '["調暗燈光躺好","輪流說明天的一個計畫","一起想像那個畫面","溫柔晚安收尾"]', '["他期待明天的什麼？"]', NULL, '期待明天，先好好睡覺，晚安。',
 42, 60,
 '{}', '{}', '{"canHaveConversation"}', '{"emotional","language"}',
 'low', 'parallel', '{}', 'bedroom',
 4, 12,
 TRUE, TRUE, TRUE,
 'calm_down', FALSE, TRUE);
