-- ============================================================================
-- Seed（自動產生，請勿手改；改 scripts/content/activities-12-24m.mjs 後重跑 build-seed.mjs）
-- 批次：20260624030000_seed_activity_library_12_24m
-- 共 24 筆。所有欄位值已通過 schema 允許集合驗證。
-- ============================================================================

INSERT INTO public.companion_activities (
  title, description, opening_line, steps, follow_up_questions, safety_notes, ending_line,
  min_age_months, max_age_months,
  required_capabilities, optional_capabilities, zpd_targets, developmental_focus,
  stimulation_level, play_type, required_resources, space_requirement,
  min_duration_minutes, max_duration_minutes,
  is_bedtime_safe, is_sick_day_safe, elderly_friendly,
  companion_type, is_fallback, is_active
) VALUES
('走走拿玩具', '在不遠處放玩具，鼓勵剛會走的寶寶走過去拿，練習平衡。', '玩具在那邊，自己走過去拿拿看～', '["讓寶寶站穩","在幾步外放他喜歡的玩具","張開手鼓勵他走過來","到了給大大的擁抱"]', '["他能連走幾步？"]', '地面平整淨空、移開硬角家具、在旁保護。', '走得越來越穩了，好棒！',
 12, 18,
 '{"canWalkIndependently"}', '{}', '{}', '{"gross_motor"}',
 'medium', 'parallel', '{}', 'living_room',
 3, 10,
 FALSE, FALSE, TRUE,
 'play', FALSE, TRUE),

('蠟筆塗鴉初體驗', '用粗蠟筆在大紙上自由塗畫，練習握筆與手眼協調。', '我們來畫畫，紅紅綠綠塗滿滿！', '["鋪大張紙、給好握的粗蠟筆","示範隨意畫線、畫圈","讓他自由塗鴉","描述他畫的顏色"]', '["他最愛哪個顏色？"]', '用無毒可水洗蠟筆，全程看顧避免入口。', '畫得真精彩，貼起來欣賞！',
 13, 20,
 '{}', '{}', '{"canScribble"}', '{"fine_motor"}',
 'low', 'solitary', '{}', 'anywhere',
 4, 12,
 TRUE, TRUE, TRUE,
 'creative', FALSE, TRUE),

('疊積木比高', '練習把積木一塊塊往上疊，挑戰能疊幾塊。', '我們來疊高高，可以疊幾塊呢？', '["給幾塊好疊的大積木","示範疊兩三塊","讓他自己疊","一起數數疊了幾塊"]', '["他能疊幾塊不倒？"]', '積木無小零件、邊角圓鈍。', '疊得好高，厲害的小工程師！',
 12, 20,
 '{}', '{}', '{"canStackBlocks3"}', '{"fine_motor"}',
 'low', 'solitary', '{}', 'anywhere',
 4, 12,
 TRUE, TRUE, TRUE,
 'play', FALSE, TRUE),

('這是什麼呀', '指著日常物品問「這是什麼」，鼓勵寶寶說出名稱、擴充詞彙。', '這是什麼呀？你來告訴我～', '["指著熟悉物品問名稱","等他回答或示範說一次","他說出就熱情肯定","換下一樣東西"]', '["他會說哪些新詞了？"]', NULL, '你會說好多詞了，真棒！',
 12, 22,
 '{}', '{}', '{"hasVocabulary10"}', '{"language"}',
 'low', 'parallel', '{}', 'anywhere',
 3, 8,
 TRUE, TRUE, TRUE,
 'talk', FALSE, TRUE),

('踢踢小球', '把球放腳邊鼓勵寶寶踢，練習單腳平衡與下肢力量。', '用腳踢踢看，球球滾出去囉！', '["把軟球放在寶寶腳前","示範輕踢一下","扶著他練習踢","球滾出去一起歡呼"]', '["他踢到球了嗎？"]', '球柔軟、場地淨空、在旁穩住避免跌倒。', '踢得真好，小小足球員！',
 14, 22,
 '{"canWalkIndependently"}', '{}', '{}', '{"gross_motor"}',
 'medium', 'parallel', '{}', 'living_room',
 3, 10,
 FALSE, FALSE, TRUE,
 'play', FALSE, TRUE),

('形狀放進洞', '玩形狀配對盒，把形狀塊放進對應的洞，練習配對與手腕轉動。', '圓圓的放這個洞，找找看～', '["拿形狀配對盒與大形狀塊","示範把圓形放進圓洞","讓他嘗試配對","放對了一起拍手"]', '["他最先學會哪個形狀？"]', '形狀塊需大於口腔、無小零件。', '配對成功，好聰明！',
 14, 24,
 '{}', '{}', '{"canPincerGrip"}', '{"fine_motor","social_cognitive"}',
 'low', 'solitary', '{}', 'anywhere',
 4, 12,
 TRUE, TRUE, TRUE,
 'play', FALSE, TRUE),

('學動物走路', '模仿小狗爬、兔子跳、大象走，結合大動作與模仿想像。', '我們來學小動物走路，汪汪～', '["示範學小狗在地上爬","換兔子雙腳跳","再學大象慢慢走","讓他跟著模仿"]', '["他最愛學哪種動物？"]', '在軟墊或淨空區進行、在旁保護。', '動物模仿秀好精彩！',
 15, 24,
 '{"canWalkIndependently"}', '{}', '{}', '{"gross_motor","social_cognitive"}',
 'high', 'parallel', '{}', 'living_room',
 3, 10,
 FALSE, FALSE, FALSE,
 'play', FALSE, TRUE),

('丟球進籃', '把球丟進大盆或籃子，練習瞄準、放手與手眼協調。', '瞄準籃子，球球投進去！', '["放一個大盆或籃子在近處","給寶寶幾顆軟球","示範丟進去","投進了一起歡呼"]', '["他投進幾顆？"]', '球柔軟、籃子穩固不傾倒。', '投籃高手，太厲害了！',
 14, 24,
 '{}', '{}', '{}', '{"gross_motor","fine_motor"}',
 'medium', 'parallel', '{}', 'living_room',
 3, 10,
 FALSE, TRUE, TRUE,
 'play', FALSE, TRUE),

('大塊拼圖', '玩 2–4 片的大塊拼圖，練習觀察、配對與問題解決。', '這片放哪裡呢？我們一起拼！', '["選 2–4 片的大塊拼圖","示範拼一片","引導他觀察形狀與圖案","完成一起喝采"]', '["他能自己拼幾片？"]', '拼片夠大、無小零件。', '拼好了，好厲害的小偵探！',
 16, 26,
 '{}', '{}', '{}', '{"fine_motor","social_cognitive"}',
 'low', 'solitary', '{}', 'anywhere',
 4, 12,
 TRUE, TRUE, TRUE,
 'play', FALSE, TRUE),

('情緒繪本共讀', '讀有情緒表情的繪本，指著臉問「他是開心還是難過」。', '看看書裡的小朋友，他現在什麼心情？', '["選有臉部表情的繪本","指著角色問情緒","示範說「他很開心」","連結到他自己的感受"]', '["他能說出幾種心情？"]', NULL, '你越來越懂心情了，真棒。',
 15, 26,
 '{}', '{}', '{}', '{"emotional","language"}',
 'low', 'parallel', '{}', 'anywhere',
 4, 12,
 TRUE, TRUE, TRUE,
 'read', FALSE, TRUE),

('推拉玩具散步', '推或拉有輪子的玩具走，練習穩定行走與控制方向。', '推著小車車，我們去散步囉～', '["給一個推拉玩具","示範推著往前走","讓他控制方向繞一圈","描述「走、停、轉彎」"]', '["他能控制方向嗎？"]', '路徑淨空、地面平整、在旁保護。', '推著走真穩，好棒！',
 13, 22,
 '{"canWalkIndependently"}', '{}', '{}', '{"gross_motor"}',
 'medium', 'solitary', '{}', 'living_room',
 3, 10,
 FALSE, FALSE, TRUE,
 'play', FALSE, TRUE),

('動作兒歌', '唱「頭兒肩膀膝腳趾」等動作兒歌，連結語言、身體部位與模仿。', '頭兒、肩膀、膝、腳趾，一起唱！', '["唱動作兒歌示範指部位","握他的手一起指","放慢讓他跟上","反覆加深記憶"]', '["他會指對哪些部位？"]', NULL, '唱跳得真好，再來一次！',
 14, 26,
 '{}', '{}', '{"imitatesActions"}', '{"language","gross_motor"}',
 'medium', 'parallel', '{}', 'anywhere',
 3, 8,
 FALSE, TRUE, TRUE,
 'music', FALSE, TRUE),

('兩個字說說看', '把單詞擴成兩字短句示範，鼓勵孩子說出「要喝」「車車來」。', '你說「車」，我們再加一個字：「車車來」！', '["聽孩子說出單詞","示範擴成兩字句","鼓勵他跟著說","在生活中自然重複"]', '["他開始說兩個字了嗎？"]', NULL, '會說短句了，好厲害！',
 18, 28,
 '{}', '{}', '{"usesTwoWordPhrases"}', '{"language"}',
 'low', 'parallel', '{}', 'anywhere',
 3, 10,
 TRUE, TRUE, TRUE,
 'talk', FALSE, TRUE),

('假扮煮飯飯', '用玩具鍋碗假裝煮飯、餵娃娃，發展假扮遊戲與語言。', '我們來煮飯飯，今天煮什麼好呢？', '["擺出玩具廚具","假裝切菜、攪拌、煮","邀孩子餵娃娃或你吃","描述動作與味道"]', '["他想出什麼假扮情節？"]', '玩具無小零件、無尖角。', '煮得真好吃，謝謝小廚師！',
 18, 30,
 '{}', '{}', '{"symbolicPlay"}', '{"social_cognitive","language"}',
 'low', 'parallel', '{}', 'anywhere',
 5, 15,
 TRUE, TRUE, TRUE,
 'creative', FALSE, TRUE),

('輪流堆積木', '一人放一塊輪流堆塔，練習等待與輪流的社交規則。', '換我放一塊，再換你，一人一次喔～', '["說明「輪流放」的規則","你放一塊再請他放","等待時數「一、二」","塔倒了一起笑著重來"]', '["他能等待輪到自己嗎？"]', '積木無小零件。', '會輪流了，真有耐心！',
 18, 30,
 '{}', '{}', '{"canTakeTurns"}', '{"social_cognitive"}',
 'low', 'cooperative', '{}', 'anywhere',
 4, 12,
 TRUE, TRUE, TRUE,
 'play', FALSE, TRUE),

('扶著爬樓梯', '扶著扶手或大人手，練習一階一階上下樓梯。', '抓好扶手，我們一階一階上樓～', '["牽手或讓他扶穩扶手","一階一階慢慢上","數「一階、二階」","下樓更小心、面向階梯"]', '["他上下幾階了？"]', '⚠️ 全程牽手或緊貼保護、絕不放手；裝設樓梯防護欄。', '爬樓梯好棒，腳力越來越好！',
 18, 28,
 '{"canWalkIndependently"}', '{}', '{"canClimbStairs"}', '{"gross_motor"}',
 'medium', 'parallel', '{}', 'anywhere',
 3, 8,
 FALSE, FALSE, FALSE,
 'play', FALSE, TRUE),

('分顏色排排站', '把同色的物品分在一起，練習顏色辨識與分類。', '紅色的放這邊，藍色的放那邊～', '["準備兩三種顏色的安全物件","示範依顏色分類","讓他把同色放一起","說出顏色名稱"]', '["他分對了幾種顏色？"]', '物件大於口腔、無小零件。', '分得真整齊，好聰明！',
 18, 30,
 '{}', '{}', '{}', '{"social_cognitive","fine_motor"}',
 'low', 'solitary', '{}', 'anywhere',
 4, 12,
 TRUE, TRUE, TRUE,
 'play', FALSE, TRUE),

('追泡泡跑', '吹泡泡讓孩子追、拍，練習跑動、瞄準與大笑放電。', '泡泡飛起來囉，快去追、去拍！', '["在安全空地吹泡泡","鼓勵孩子追著拍破","比比看誰拍到多","玩到開心為止"]', '["他拍破幾個泡泡？"]', '地面防滑乾燥、場地淨空；泡泡水勿入口眼。', '追泡泡好開心，跑得真快！',
 18, 36,
 '{"canWalkIndependently"}', '{}', '{}', '{"gross_motor"}',
 'high', 'parallel', '{}', 'outdoor',
 4, 12,
 FALSE, FALSE, FALSE,
 'outdoor', FALSE, TRUE),

('貼紙貼貼樂', '撕貼紙貼到紙上指定位置，練習拇指食指與專注。', '撕下貼紙，貼到這裡來～', '["給大張貼紙與底紙","示範撕下貼好","讓他撕貼、自由創作","欣賞他的貼紙畫"]', '["他能自己撕下貼紙嗎？"]', '貼紙夠大、全程看顧避免入口。', '貼紙畫好美，貼起來展示！',
 18, 30,
 '{}', '{}', '{"canPincerGrip"}', '{"fine_motor"}',
 'low', 'solitary', '{}', 'anywhere',
 4, 12,
 TRUE, TRUE, TRUE,
 'creative', FALSE, TRUE),

('假裝打電話', '用玩具電話假裝通話，發展假扮、語言與社交對話。', '鈴鈴～電話響了，喂？你好！', '["拿玩具或手作電話","假裝撥號、說「喂」","一問一答來回對話","請他打給娃娃或家人"]', '["他會說哪些對話？"]', NULL, '講電話好有禮貌，再見囉！',
 18, 30,
 '{}', '{}', '{"usesTwoWordPhrases","symbolicPlay"}', '{"language","social_cognitive"}',
 'low', 'cooperative', '{}', 'anywhere',
 4, 12,
 TRUE, TRUE, TRUE,
 'talk', FALSE, TRUE),

('收玩具歌', '邊唱收拾歌邊把玩具歸位，建立routine與責任感。', '玩具玩具回家囉，我們一起收～', '["玩完唱固定的「收玩具歌」","示範把玩具放回籃子","邀孩子一起收","收完給大大的讚"]', '["他願意一起收嗎？"]', NULL, '收得真乾淨，好棒的幫手！',
 18, 36,
 '{}', '{}', '{}', '{"social_cognitive","emotional"}',
 'low', 'cooperative', '{}', 'anywhere',
 3, 8,
 TRUE, TRUE, TRUE,
 'play', FALSE, TRUE),

('等一下也沒關係', '用短暫等待的小遊戲，練習承受「等一下」的小挫折。', '數到三才能拿喔，一、二、三，給你！', '["拿他想要的安全物件","說「等一下，數到三」","一起數到三再給","逐漸拉長一點等待"]', '["他能等多久不哭鬧？"]', '等待時間短、保持輕鬆，避免造成挫折過度。', '會等一下了，好有耐心！',
 20, 34,
 '{}', '{}', '{"toleratesFrustration"}', '{"emotional","social_cognitive"}',
 'low', 'parallel', '{}', 'anywhere',
 2, 8,
 TRUE, TRUE, TRUE,
 'play', FALSE, TRUE),

('心情臉譜', '做開心、難過、生氣的表情讓孩子認，命名情緒。', '看我的臉，這是開心還是生氣呢？', '["做誇張的情緒表情","問孩子「這是什麼心情」","示範說出情緒詞","請他也做做看"]', '["他能認出幾種情緒？"]', NULL, '你好會看心情，真棒！',
 18, 36,
 '{}', '{}', '{}', '{"emotional","social_cognitive"}',
 'low', 'parallel', '{}', 'anywhere',
 3, 8,
 TRUE, TRUE, TRUE,
 'talk', FALSE, TRUE),

('睡前說今天', '睡前用簡單句子回顧今天做了什麼，連結語言、記憶與安定。', '躺好，我們說說今天玩了什麼～', '["調暗燈光、躺下","用簡單句說今天的事","停頓讓他補一兩個字","以溫柔的晚安收尾"]', '["他記得今天哪件事？"]', NULL, '今天很棒，晚安囉。',
 20, 40,
 '{}', '{}', '{"usesTwoWordPhrases"}', '{"language","emotional"}',
 'low', 'parallel', '{}', 'bedroom',
 4, 12,
 TRUE, TRUE, TRUE,
 'calm_down', FALSE, TRUE);
