-- ============================================================================
-- Seed（自動產生，請勿手改；改 scripts/content/activities-24-36m.mjs 後重跑 build-seed.mjs）
-- 批次：20260624040000_seed_activity_library_24_36m
-- 共 23 筆。所有欄位值已通過 schema 允許集合驗證。
-- ============================================================================

INSERT INTO public.companion_activities (
  title, description, opening_line, steps, follow_up_questions, safety_notes, ending_line,
  min_age_months, max_age_months,
  required_capabilities, optional_capabilities, zpd_targets, developmental_focus,
  stimulation_level, play_type, required_resources, space_requirement,
  min_duration_minutes, max_duration_minutes,
  is_bedtime_safe, is_sick_day_safe, elderly_friendly,
  companion_type, is_fallback, is_active
) VALUES
('學青蛙跳', '蹲下雙腳一起往前跳，練習雙腳跳與下肢爆發力。', '我們來學青蛙，呱呱跳跳跳！', '["示範蹲下雙腳一起跳","牽手帶他一起跳","放手讓他自己跳","比比看跳多遠"]', '["他能雙腳同時離地嗎？"]', '在軟墊或淨空平地、在旁保護避免跌坐。', '跳得真高，小青蛙好棒！',
 24, 36,
 '{"canRun"}', '{}', '{"canJumpBothFeet"}', '{"gross_motor"}',
 'high', 'parallel', '{}', 'living_room',
 3, 10,
 FALSE, FALSE, FALSE,
 'play', FALSE, TRUE),

('畫圈圈', '示範畫圓，鼓勵孩子嘗試畫出封閉的圈，練習運筆控制。', '我們來畫圈圈，繞一圈接起來～', '["示範慢慢畫一個圓","牽他的手畫一次","讓他自己試","把圓變成太陽或臉"]', '["他畫的圈接起來了嗎？"]', '用無毒可水洗筆。', '畫圈圈好棒，變成笑臉了！',
 28, 40,
 '{}', '{}', '{"canDrawCircle"}', '{"fine_motor"}',
 'low', 'solitary', '{}', 'anywhere',
 4, 12,
 TRUE, TRUE, TRUE,
 'creative', FALSE, TRUE),

('說完整的話', '把孩子的短句擴成完整句子示範，鼓勵用三四個字表達。', '你說「要餅乾」，我們說「我要吃餅乾」！', '["聽孩子表達需求","示範擴成完整句子","鼓勵他跟著說一次","生活中持續示範"]', '["他開始說較長的句子了嗎？"]', NULL, '說得好完整，越來越會講了！',
 28, 42,
 '{}', '{}', '{"usesSentences"}', '{"language"}',
 'low', 'parallel', '{}', 'anywhere',
 3, 10,
 TRUE, TRUE, TRUE,
 'talk', FALSE, TRUE),

('假扮看醫生', '輪流當醫生與病人，用玩具聽診器假扮看診，發展假扮與同理。', '醫生你好，我肚子痛痛，幫我看看～', '["準備玩具醫生組","輪流當醫生與病人","假裝聽診、打針、安慰","互換角色再玩"]', '["他演醫生時說了什麼？"]', '玩具無小零件、無尖角。', '謝謝小醫生，我好多了！',
 24, 42,
 '{}', '{}', '{"symbolicPlay"}', '{"social_cognitive","language"}',
 'low', 'cooperative', '{}', 'anywhere',
 5, 15,
 TRUE, TRUE, TRUE,
 'creative', FALSE, TRUE),

('走直線平衡', '沿地上的線或膠帶走，練習平衡與身體控制。', '走在線上不要掉下去，慢慢走～', '["在地上貼一條直線","示範張開手走線","牽手陪他走一次","讓他自己挑戰"]', '["他能走幾步不偏離？"]', '地面防滑、周圍淨空、在旁保護。', '平衡感真好，走得好穩！',
 24, 40,
 '{"canWalkIndependently"}', '{}', '{}', '{"gross_motor"}',
 'medium', 'solitary', '{}', 'living_room',
 3, 10,
 FALSE, TRUE, TRUE,
 'play', FALSE, TRUE),

('串大珠子', '把大珠子串到繩子上，練習雙手協調與專注。', '一顆一顆穿起來，做條漂亮項鍊！', '["給大珠子與硬頭粗繩","示範穿一顆","讓他自己穿","數數穿了幾顆"]', '["他能自己穿過洞嗎？"]', '珠子需大於口腔、無法吞食；繩子短、全程看顧避免纏繞。', '項鍊好美，你好厲害！',
 26, 42,
 '{}', '{}', '{"canPincerGrip"}', '{"fine_motor"}',
 'low', 'solitary', '{}', 'anywhere',
 5, 15,
 TRUE, TRUE, TRUE,
 'creative', FALSE, TRUE),

('數數一二三', '一起數樓梯、點心、玩具，建立數字與數量的連結。', '我們來數數看，有幾個呀？一、二、三～', '["指著物品一個個數","請孩子跟著數","問「總共幾個」","在生活中常常數"]', '["他能數到幾？"]', NULL, '數得真好，你會數數了！',
 24, 40,
 '{}', '{}', '{}', '{"social_cognitive","language"}',
 'low', 'parallel', '{}', 'anywhere',
 3, 10,
 TRUE, TRUE, TRUE,
 'talk', FALSE, TRUE),

('黏土搓搓捏捏', '搓圓、壓扁、捏形狀，強化手部肌肉與創造力。', '黏土軟軟的，我們來捏小東西！', '["給安全無毒黏土","示範搓圓、壓扁、搓長條","讓他自由創作","一起說做了什麼"]', '["他做出什麼作品？"]', '用無毒黏土、全程看顧避免入口；玩後洗手。', '捏得好有創意，真棒！',
 24, 42,
 '{}', '{}', '{}', '{"fine_motor"}',
 'low', 'solitary', '{}', 'kitchen',
 5, 15,
 TRUE, TRUE, TRUE,
 'creative', FALSE, TRUE),

('躲貓貓數到十', '一人躲、一人數到十再找，練習數數、輪流與大動作。', '我數到十，你快去躲，準備好囉！', '["約定安全的躲藏範圍","一人遮眼數到十","另一人躲起來","找到後互換角色"]', '["他會找哪些地方躲？"]', '限定安全範圍、移開危險物、避免躲進密閉空間。', '找到你了，玩得好開心！',
 28, 44,
 '{"canRun"}', '{}', '{"canTakeTurns"}', '{"gross_motor","social_cognitive"}',
 'high', 'cooperative', '{}', 'anywhere',
 5, 15,
 FALSE, FALSE, FALSE,
 'play', FALSE, TRUE),

('假扮小商店', '擺出商品玩買賣，輪流當老闆與客人，發展語言、數量與社交。', '歡迎光臨！你想買什麼呢？', '["擺出玩具或安全物品當商品","輪流當老闆與客人","假裝付錢、找錢、道謝","互換角色"]', '["他會說哪些買賣對話？"]', '道具無小零件。', '謝謝光臨，歡迎下次再來！',
 28, 44,
 '{}', '{}', '{"usesSentences","symbolicPlay"}', '{"social_cognitive","language"}',
 'low', 'cooperative', '{}', 'anywhere',
 5, 15,
 TRUE, TRUE, TRUE,
 'creative', FALSE, TRUE),

('生氣了怎麼辦', '在孩子受挫時陪他命名情緒、練習深呼吸與簡單因應。', '你很生氣對不對？我們一起深呼吸～', '["蹲下與孩子平視、接納情緒","幫他說出「你很生氣／失望」","一起做三次深呼吸","冷靜後討論怎麼辦"]', '["什麼方法最能幫他冷靜？"]', '先確保安全；情緒激烈時先陪伴不說教。', '情緒過去了，你做得很好。',
 24, 48,
 '{}', '{}', '{"toleratesFrustration"}', '{"emotional"}',
 'low', 'parallel', '{}', 'anywhere',
 3, 10,
 TRUE, TRUE, TRUE,
 'calm_down', FALSE, TRUE),

('唱跳律動', '跟著音樂做動作律動，練習節奏感、協調與模仿。', '音樂來囉，我們一起扭一扭、跳一跳！', '["放輕快的兒歌","示範拍手、轉圈、踏步","讓孩子跟著做","自由發揮自己的舞步"]', '["他最愛哪個動作？"]', '場地淨空防滑、避免過度興奮跌倒。', '跳得真好，小舞星！',
 24, 44,
 '{"canWalkIndependently"}', '{}', '{}', '{"gross_motor","social_cognitive"}',
 'high', 'parallel', '{}', 'living_room',
 3, 12,
 FALSE, FALSE, TRUE,
 'music', FALSE, TRUE),

('大中小排排看', '把同類物品依大小排序，建立大小與序列概念。', '哪個最大？哪個最小？排排看～', '["拿三個大小不同的同類物","示範由大到小排","讓他自己排","說「大、中、小」"]', '["他能正確排序嗎？"]', '物件大於口腔、無小零件。', '排得真整齊，好聰明！',
 26, 42,
 '{}', '{}', '{}', '{"social_cognitive","fine_motor"}',
 'low', 'solitary', '{}', 'anywhere',
 4, 12,
 TRUE, TRUE, TRUE,
 'play', FALSE, TRUE),

('倒水玩一玩', '在容器間倒水，練習手腕控制、專注與容量概念。', '把水倒過去，不要灑出來喔～', '["準備兩個杯子與少量水","示範慢慢倒","讓他練習倒來倒去","描述「滿了、空了」"]', '["他倒得越來越穩嗎？"]', '少量水、地面防滑、避免滑倒；全程看顧。', '倒得好穩，手好巧！',
 26, 42,
 '{}', '{}', '{}', '{"fine_motor","social_cognitive"}',
 'low', 'solitary', '{}', 'kitchen',
 4, 12,
 TRUE, TRUE, TRUE,
 'sensory', FALSE, TRUE),

('聽指令做動作', '說「摸摸頭」「拍拍手」讓孩子照做，練習聽理解與身體控制。', '聽我說，摸摸頭！再來，拍拍手！', '["給一個簡單指令","孩子照做就稱讚","加入兩步指令「先跳再轉圈」","輪流由孩子當指揮"]', '["他能記得兩步指令嗎？"]', '動作幅度安全、場地淨空。', '都聽懂了，反應好快！',
 24, 42,
 '{}', '{}', '{}', '{"language","gross_motor"}',
 'medium', 'parallel', '{}', 'anywhere',
 3, 10,
 FALSE, TRUE, TRUE,
 'play', FALSE, TRUE),

('滾球保齡球', '排好寶特瓶當球瓶，滾球撞倒，練習瞄準與因果。', '瞄準球瓶，把它們通通滾倒！', '["用空寶特瓶排成球瓶","示範滾球撞倒","讓孩子試著瞄準","數數倒了幾瓶"]', '["他一次撞倒幾瓶？"]', '瓶子輕空、球柔軟、場地淨空。', '全倒！保齡球高手！',
 26, 44,
 '{}', '{}', '{}', '{"gross_motor","social_cognitive"}',
 'medium', 'cooperative', '{}', 'living_room',
 4, 12,
 FALSE, TRUE, TRUE,
 'play', FALSE, TRUE),

('蓋印章作畫', '用印章或蔬果切面沾顏料蓋印，練習手部控制與創意。', '蓋一個、蓋一個，變出一幅畫！', '["準備安全印章與可水洗顏料","示範沾色蓋印","讓他自由蓋出圖案","一起欣賞作品"]', '["他蓋出什麼圖案？"]', '顏料無毒可水洗、全程看顧避免入口；鋪好桌面。', '蓋印畫好美，展示起來！',
 26, 44,
 '{}', '{}', '{}', '{"fine_motor"}',
 'low', 'solitary', '{}', 'kitchen',
 5, 15,
 TRUE, TRUE, TRUE,
 'creative', FALSE, TRUE),

('紅綠燈走走停', '喊「綠燈走、紅燈停」讓孩子跑動與急停，練習聽指令與自我控制。', '綠燈走～紅燈，停！', '["說明綠燈走、紅燈停","喊綠燈讓他走或跑","突然喊紅燈要立刻停","互換當紅綠燈"]', '["他能聽到紅燈馬上停嗎？"]', '場地淨空防滑、控制速度避免衝撞。', '反應好快，紅燈都停得住！',
 28, 46,
 '{"canRun"}', '{}', '{"toleratesFrustration"}', '{"gross_motor","social_cognitive"}',
 'high', 'cooperative', '{}', 'outdoor',
 4, 12,
 FALSE, FALSE, FALSE,
 'outdoor', FALSE, TRUE),

('我是小幫手', '邀孩子幫忙簡單家事（擦桌、放餐具），培養責任與成就感。', '你願意當小幫手嗎？我們一起擦桌子！', '["挑一件安全的小家事","示範怎麼做","陪他一起完成","完成後具體稱讚"]', '["他喜歡幫哪件忙？"]', '挑安全任務、避開刀具熱源與清潔劑。', '謝謝小幫手，幫了大忙！',
 24, 48,
 '{}', '{}', '{}', '{"social_cognitive","emotional"}',
 'low', 'cooperative', '{}', 'kitchen',
 4, 12,
 TRUE, TRUE, TRUE,
 'play', FALSE, TRUE),

('動物配對卡', '把相同的動物卡配成一對，練習觀察、記憶與配對。', '找找看，哪兩張是一樣的動物？', '["準備幾組成對的圖卡","翻開示範找一對","讓他找出相同的","說出動物名稱"]', '["他配對得越來越快嗎？"]', '卡片邊角圓鈍。', '配對成功，記性真好！',
 26, 44,
 '{}', '{}', '{}', '{"social_cognitive","language"}',
 'low', 'cooperative', '{}', 'anywhere',
 4, 12,
 TRUE, TRUE, TRUE,
 'play', FALSE, TRUE),

('畫畫說故事', '邊塗鴉邊請孩子說「這是什麼」，連結圖畫與口語敘事。', '你畫的是什麼呀？說給我聽～', '["一起自由塗鴉","問他畫的是什麼","把他的話寫在旁邊唸出來","串成一個小故事"]', '["他編了什麼故事？"]', '用無毒可水洗筆。', '故事好精彩，你是小作家！',
 30, 46,
 '{}', '{}', '{"usesSentences"}', '{"language","fine_motor"}',
 'low', 'parallel', '{}', 'anywhere',
 5, 15,
 TRUE, TRUE, TRUE,
 'creative', FALSE, TRUE),

('形狀尋寶', '在家找出圓形、方形的東西，結合形狀認知與走動探索。', '我們來找圓形的東西，看誰先找到！', '["指定一個形狀","一起在家裡找符合的物品","找到就說出名稱","換下一個形狀"]', '["他找到哪些形狀的東西？"]', '避免拿取危險或易碎物品。', '找到好多形狀，眼力真好！',
 28, 46,
 '{"canWalkIndependently"}', '{}', '{}', '{"social_cognitive","gross_motor"}',
 'medium', 'cooperative', '{}', 'anywhere',
 4, 12,
 FALSE, TRUE, TRUE,
 'play', FALSE, TRUE),

('睡前三件開心事', '睡前說出今天三件開心的事，培養正向回顧與表達。', '躺好，說說今天有哪三件開心的事？', '["調暗燈光躺好","輪流說一件今天開心的事","一起回想細節","以溫柔晚安收尾"]', '["他記得哪件最開心？"]', NULL, '今天好棒，晚安做個好夢。',
 30, 54,
 '{}', '{}', '{"usesSentences"}', '{"emotional","language"}',
 'low', 'parallel', '{}', 'bedroom',
 4, 12,
 TRUE, TRUE, TRUE,
 'calm_down', FALSE, TRUE);
